/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlockLogDto } from '../models/block-log-dto';
export interface AdminDto {

  /**
   * 내가 차단 당한 로그
   */
  blockedLogs: Array<BlockLogDto> | null;

  /**
   * 관리자 생성일
   */
  createdAt: string;

  /**
   * 관리자 이메일
   */
  email: string;

  /**
   * 관리자 ID
   */
  id: string;

  /**
   * 관리자 이름
   */
  name: string;

  /**
   * 리프레시 토큰
   */
  refreshToken: string;

  /**
   * 권한
   */
  role: 'SUPER_ADMIN' | 'NORMAL';

  /**
   * 순번
   */
  rowNumber: number;

  /**
   * 관리자 상태
   */
  status: 'ACTIVE' | 'BLOCKED';

  /**
   * 관리자 수정일
   */
  updatedAt: string;
}
