/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthDto {

  /**
   * Auth 제공자 이메일
   */
  email: string;

  /**
   * Auth 아이디
   */
  id: string;

  /**
   * Auth 제공자
   */
  provider: 'EMAIL' | 'KAKAO' | 'NAVER' | 'GOOGLE' | 'APPLE';
}
