/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BannerReorderDto {

  /**
   * current
   */
  current: number;

  /**
   * mode
   */
  mode?: string;

  /**
   * prev
   */
  prev: number;
}
