/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
export interface BannerCreateDto {

  /**
   * 노출 여부
   */
  isExposed?: boolean;

  /**
   * 배너 모바일 이미지
   */
  mobileImage: FileDto;

  /**
   * 모드(웹용/모바일용)
   */
  mode?: string;

  /**
   * 정렬 순서
   */
  order?: number;

  /**
   * 배너 pc 이미지
   */
  pcImage: FileDto;

  /**
   * 배너 제목
   */
  title: string;

  /**
   * 링크
   */
  url?: string;
}
