/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
import { UserDto } from '../models/user-dto';
export interface BannerDto {

  /**
   * 작성자
   */
  admin: UserDto;

  /**
   * 생성일
   */
  createdAt: string;

  /**
   * 배너 ID
   */
  id: string;

  /**
   * 노출 여부
   */
  isExposed: boolean;

  /**
   * 배너 모바일 이미지
   */
  mobileImage: FileDto;

  /**
   * 모드(웹용/모바일용)
   */
  mode: string;

  /**
   * 정렬 순서
   */
  order: number;

  /**
   * 배너 pc 이미지
   */
  pcImage: FileDto;

  /**
   * rowNumber
   */
  rowNumber: string;

  /**
   * 텍스트컬러
   */
  textColor: string;

  /**
   * 제목
   */
  title: string;

  /**
   * 수정일
   */
  updatedAt: string;

  /**
   * URL
   */
  url: string;
}
