/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookmarkDto {
  createdAt: string;
  id: string;
  modelId: string;
  modelName: '\uBC1C\uC8FC\uACC4\uD68D' | '\uC0AC\uC804\uADDC\uACA9' | '\uC785\uCC30\uACF5\uACE0';
}
