/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactValidationDto {

  /**
   * 전화번호
   */
  contact: string;

  /**
   * 사용자 이름
   */
  name?: string;
}
