/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateNoticeDto {

  /**
   * 내용
   */
  content: string;

  /**
   * 고정
   */
  isPinned: boolean;

  /**
   * 제목
   */
  title: string;
}
