/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateRoleDto {

  /**
   * 설명
   */
  description?: string;

  /**
   * 이름
   */
  name: string;
}
