/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMenuDto {

  /**
   * api URL
   */
  apiUrl: string;

  /**
   * 메뉴명
   */
  name: string;

  /**
   * 페이지 유형
   */
  pageType: 'READ' | 'CREATE' | 'UPDATE';

  /**
   * 상위 메뉴 ID
   */
  parentId?: string;

  /**
   * 라우트 URL
   */
  routeUrl: string;
}
