/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CursorPaginationDto {

  /**
   * 다음 페이지 존재 여부
   */
  hasNext: boolean;
  items: Array<Array<any>>;

  /**
   * 다음 커서
   */
  nextCursor?: string;
}
