/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FaqDto } from '../models/faq-dto';
import { PageInfoDto } from '../models/page-info-dto';
export interface FaqSearchResponseDto {
  items: Array<FaqDto>;
  pageInfo: PageInfoDto;
}
