/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileInfoResponseDto {

  /**
   * The filename extracted from the URL
   */
  filename: string;
}
