/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FindEmailResponseDto {

  /**
   * 등록 일자
   */
  createdAt: string;

  /**
   * 이메일
   */
  email: string;

  /**
   * 제공자
   */
  provider: 'EMAIL' | 'KAKAO' | 'NAVER' | 'GOOGLE' | 'APPLE';
}
