/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface InquiryDto {

  /**
   * 답변
   */
  answer?: string;

  /**
   * 답변일
   */
  answeredAt?: string;

  /**
   * 내용
   */
  content: string;

  /**
   * 생성일
   */
  createdAt: string;

  /**
   * ID
   */
  id: string;

  /**
   * 순번
   */
  rowNumber: string;

  /**
   * 제목
   */
  title: string;

  /**
   * 수정일
   */
  updatedAt: string;

  /**
   * 등록 회원
   */
  user?: UserDto;
}
