/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MenuPermissionDto } from '../models/menu-permission-dto';
export interface MenuDto {

  /**
   * Api URL
   */
  apiUrl: string;

  /**
   * 자식 메뉴
   */
  children: Array<MenuDto>;

  /**
   * 메뉴 생성일
   */
  createdAt: string;

  /**
   * 메뉴 ID
   */
  id: string;

  /**
   * 메뉴명
   */
  name: string;

  /**
   * 페이지 유형
   */
  pageType: 'READ' | 'CREATE' | 'UPDATE';

  /**
   * 부모 메뉴
   */
  parent: MenuDto;

  /**
   * 부모 메뉴 ID
   */
  parentId: string;

  /**
   * 메뉴 권한
   */
  permissions: Array<MenuPermissionDto>;

  /**
   * 라우트 URL
   */
  routeUrl: string;

  /**
   * 메뉴 수정일
   */
  updatedAt: string;
}
