/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface NoticeDto {

  /**
   * 작성 관리자
   */
  admin: UserDto;

  /**
   * 내용
   */
  content: string;

  /**
   * 등록일
   */
  createdAt: string;

  /**
   * ID
   */
  id: string;

  /**
   * 핀 고정
   */
  isPinned: boolean;

  /**
   * rowNumber
   */
  rowNumber: string;

  /**
   * 제목
   */
  title: string;
}
