/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OauthCreateDto {

  /**
   * email 제공자
   */
  email?: string;

  /**
   * SNS 제공자
   */
  provider?: 'EMAIL' | 'KAKAO' | 'NAVER' | 'GOOGLE' | 'APPLE';

  /**
   * providerId
   */
  providerId?: string;
}
