/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderPlanDto {
  createdAt: string;
  id: string;
  keywords: Array<string>;
  updatedAt: string;
  '게시일시': string;
  '계약방법명': string;
  '공고게시여부': boolean;
  '공사기간내용': string;
  '공사지역명': string;
  '공종구분명': string;
  '규격내용': string;
  '규격항목': {
};
  '단위': string;
  '담당자명': string;
  '모집등록번호': string;
  '물품분류번호': string;
  '발주계획순번': number;
  '발주계획통합번호': string;
  '발주관급자재비': number;
  '발주국고보조금액': number;
  '발주금차도급금액': number;
  '발주기관명': string;
  '발주기관코드': string;
  '발주기타금액': number;
  '발주년도': number;
  '발주도급금액': number;
  '발주월': string;
  '부서명': string;
  '비고내용': string;
  '사업명': string;
  '설계문서열람기간내용': string;
  '설계문서열람장소명': string;
  '세부품명': string;
  '세부품명번호': string;
  '소관구분명': string;
  '소관구분코드': string;
  '수량내용': string;
  '업무구분명': string;
  '업무구분코드': string;
  '업무유형명': string;
  '업무유형코드': string;
  '예산구분코드': string;
  '용도내용': string;
  '입찰공고번호목록': string;
  '전화번호': string;
  '조달방식': string;
  '총괄기관명': string;
  '품명': string;
  '합계발주금액': number;
  '합계발주미화금액': number;
  '협정여부': boolean;
}
