/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PageInfoDto {

  /**
   * 페이지 내 항목 수
   */
  pageItems: number;

  /**
   * 페이지 번호
   */
  pageNo: number;

  /**
   * 페이지 크기
   */
  pageSize: number;

  /**
   * 총 항목 수
   */
  totalItems: number;

  /**
   * 총 페이지
   */
  totalPages: number;
}
