/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleDto } from '../models/role-dto';
export interface RoleLevelPermissionDto {

  /**
   * 기본 여부
   */
  default: boolean;

  /**
   * 설명
   */
  description: string;

  /**
   * id
   */
  id: string;

  /**
   * level
   */
  level: number;

  /**
   * permission
   */
  permission: string;

  /**
   * role
   */
  role: RoleDto;

  /**
   * 최고 권한 여부
   */
  super: boolean;
}
