/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingDto {

  /**
   * 설정 키
   */
  key: 'PRIVACY:USER_WITHDRAWN_PERIOD' | 'PRIVACY:USER_DATA_PERIOD' | 'PRIVACY:USER_BLOCKED_PERIOD' | 'COMPANY:NAME' | 'COMPANY:ADDRESS' | 'COMPANY:TEL' | 'COMPANY:EMAIL' | 'COMPANY:REGISTRATION_NUMBER' | 'COMPANY:CEO' | 'COMPANY:LOGO';

  /**
   * 설정 값
   */
  value: string;
}
