/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatisticUserDto {

  /**
   * 가입한지 3일이 지난 회원 수
   */
  threeDays: number;

  /**
   * 오늘 가입한 회원 수
   */
  today: number;

  /**
   * 가입한지 7일이 지난 회원 수
   */
  week: number;
}
