/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
export interface UpdateBusinessInfoDto {

  /**
   * 주소
   */
  address?: string;

  /**
   * 상호명
   */
  businessName?: string;

  /**
   * 사업자등록번호
   */
  businessRegistrationNumber?: string;

  /**
   * 등록일
   */
  createdAt?: string;

  /**
   * 고객 센터
   */
  customerServiceCenter?: string;

  /**
   * 이메일
   */
  email?: string;

  /**
   * ID
   */
  id?: string;

  /**
   * 로고
   */
  logo?: FileDto;

  /**
   * 대표자명
   */
  representativeName?: string;
}
