/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateRoleLevelPermissionDto {

  /**
   * description
   */
  description?: string;

  /**
   * level
   */
  level?: number;

  /**
   * permission
   */
  permission?: string;

  /**
   * 권한 ID
   */
  roleId?: string;
}
