/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePasswordDto {

  /**
   * 사용자 비밀번호 확인
   */
  confirmedPassword: string;

  /**
   * 사용자 연락처
   */
  contact?: string;

  /**
   * 기존 비밀번호
   */
  oldPassword?: string;

  /**
   * 사용자 비밀번호
   */
  password: string;

  /**
   * 토큰
   */
  token?: string;
}
