/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthDto } from '../models/auth-dto';
import { RoleLevelPermissionDto } from '../models/role-level-permission-dto';
export interface UserDto {

  /**
   * accessToken
   */
  accessToken: string;

  /**
   * 소셜 로그인 정보
   */
  auths: Array<AuthDto>;

  /**
   * 사용자 차단 여부
   */
  blocked: boolean;

  /**
   * 사용자 연락처
   */
  contact: string;

  /**
   * 사용자 등록 일자
   */
  createdAt: string;

  /**
   * 사용자 이메일
   */
  email: string;

  /**
   * 사용자 ID
   */
  id: string;

  /**
   * 사용자 이름
   */
  name: string;

  /**
   * 사용자 권한
   */
  permission: RoleLevelPermissionDto;

  /**
   * 사용자 계정 상태
   */
  status: 'ACTIVE' | 'BLOCKED' | 'WITHDRAWN' | 'REJOINABLE';

  /**
   * 사용자 수정 일자
   */
  updatedAt: string;

  /**
   * 사용자 탈퇴 일자
   */
  withdrawnAt: string | null;

  /**
   * 사용자 탈퇴 내역
   */
  withdrawnLogs: Array<string> | null;
}
