/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VerifyContactDto {

  /**
   * 인증번호
   */
  code: string;

  /**
   * 전화번호
   */
  contact: string;

  /**
   * 토큰
   */
  token: string;
}
