/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface VisitorDeviceTypeDto {

  /**
   * 방문자 수
   */
  counts: Array<number>;

  /**
   * 라벨
   */
  labels: Array<string>;
}
