/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileSearchResponseDto } from '../../models/file-search-response-dto';

export interface StorageControllerSearch$Params {

/**
 * 페이지 크기
 */
  pageSize: number;

/**
 * 정렬 기준
 */
  orderBy?: string;

/**
 * 정렬 방향
 */
  align?: 'asc' | 'desc';

/**
 * 검색어
 */
  query?: string;

/**
 * 페이지 번호
 */
  pageNo: number;

/**
 * columnId
 */
  columnId?: string;

/**
 * columnName
 */
  columnName?: string;
}

export function storageControllerSearch(http: HttpClient, rootUrl: string, params: StorageControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<FileSearchResponseDto>> {
  const rb = new RequestBuilder(rootUrl, storageControllerSearch.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('align', params.align, {});
    rb.query('query', params.query, {});
    rb.query('pageNo', params.pageNo, {});
    rb.query('columnId', params.columnId, {});
    rb.query('columnName', params.columnName, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileSearchResponseDto>;
    })
  );
}

storageControllerSearch.PATH = '/api/storage';
