/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminDto } from '../models/admin-dto';
import { PageInfoDto } from '../models/page-info-dto';
export interface AdminSearchResponseDto {
  items: Array<AdminDto>;
  pageInfo: PageInfoDto;
}
