/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BannerDto } from '../models/banner-dto';
import { PageInfoDto } from '../models/page-info-dto';
export interface BannerSearchResponseDto {
  items: Array<BannerDto>;
  pageInfo: PageInfoDto;
}
