/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BidViewDto {
  id: string;
  type: string;
  '공고규격서URL': Array<string>;
  '공고기관담당자명': string;
  '공고기관명': string;
  '공고종류명': string;
  '등록일시': string;
  '모의공고여부': boolean;
  '배정예산금액'?: number;
  '수요기관명': string;
  '업무구분명': string;
  '입찰개시일시'?: string;
  '입찰공고명': string;
  '입찰방식명': string;
  '키워드': Array<string>;
}
