/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface BlockLogDto {

  /**
   * 차단된 사용자
   */
  blockedUser: UserDto;

  /**
   * 대상 사용자 ID
   */
  blockedUserId: string;

  /**
   * 차단 진행 일자
   */
  createdAt: string;

  /**
   * 차단 로그 ID
   */
  id: string;

  /**
   * 차단 완료 일자
   */
  until: string;

  /**
   * 차단한 사용자
   */
  user: UserDto;

  /**
   * 사용자 ID
   */
  userId: string;
}
