/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMenuPermissionDto {

  /**
   * 생성 권한
   */
  canCreate: boolean;

  /**
   * 삭제 권한
   */
  canDelete: boolean;

  /**
   * 읽기 권한
   */
  canRead: boolean;

  /**
   * 수정 권한
   */
  canUpdate: boolean;

  /**
   * 레벨
   */
  level: number;

  /**
   * 역할
   */
  roleId: string;
}
