/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminDto } from '../models/admin-dto';
export interface FaqDto {

  /**
   * 관리자
   */
  admin: AdminDto;

  /**
   * 내용
   */
  content: string;

  /**
   * 등록일
   */
  createdAt: string;
  en?: {
'title'?: string;
'content'?: string;
};

  /**
   * ID
   */
  id: string;

  /**
   * 핀 고정
   */
  isPinned: boolean;
  ja?: {
'title'?: string;
'content'?: string;
};

  /**
   * rowNumber
   */
  rowNumber: string;

  /**
   * 제목
   */
  title: string;
}
