/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileDto {

  /**
   * 프로젝트 ID
   */
  ProjectId?: string;

  /**
   * 배너 ID
   */
  bannerId?: string;

  /**
   * 기업 ID
   */
  companyId?: string;

  /**
   * 문서내용
   */
  content: string;

  /**
   * 생성일
   */
  createdAt: string;

  /**
   * 파일 ID
   */
  id: string;

  /**
   * MIME 타입
   */
  mimeType: string;

  /**
   * 미션 ID
   */
  missionId?: string;

  /**
   * 미션 정보 ID
   */
  missionInfoId?: string;

  /**
   * 미션 참여 정보 ID
   */
  missionParticipationId?: string;

  /**
   * 파일명
   */
  name: string;

  /**
   * 포인트샵 ID
   */
  pointShopId?: string;

  /**
   * rowNumber
   */
  rowNumber?: string;

  /**
   * 크기
   */
  size: number;

  /**
   * 상태
   */
  status: string;

  /**
   * 문서제목
   */
  title: string;

  /**
   * 타입
   */
  type: string;

  /**
   * 수정일
   */
  updatedAt: string;

  /**
   * URL
   */
  url: string;

  /**
   * 업로드한 사용자 ID
   */
  userId?: string;
}
