/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileDto } from '../models/file-dto';
import { PageInfoDto } from '../models/page-info-dto';
export interface FileSearchResponseDto {
  items: Array<FileDto>;
  pageInfo: PageInfoDto;
}
