/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleDto } from '../models/role-dto';
export interface MenuPermissionDto {

  /**
   * 생성 권한
   */
  canCreate: boolean;

  /**
   * 삭제 권한
   */
  canDelete: boolean;

  /**
   * 읽기 권한
   */
  canRead: boolean;

  /**
   * 수정 권한
   */
  canUpdate: boolean;

  /**
   * 등록일
   */
  createdAt: string;

  /**
   * 메뉴 권한 ID
   */
  id: string;

  /**
   * 레벨
   */
  level: number;

  /**
   * 역할
   */
  role: RoleDto;

  /**
   * 수정일
   */
  updatedAt: string;
}
