/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OauthCreateDto } from '../models/oauth-create-dto';
import { UserDto } from '../models/user-dto';
export interface OAuthResponseDto {

  /**
   * 소셜 로그인 회원가입 정보
   */
  signUp: OauthCreateDto | null;

  /**
   * 로그인 상태
   */
  state: '\uC774\uBBF8\uAC00\uC785\uB41C\uACC4\uC815' | '\uB85C\uADF8\uC778\uC131\uACF5' | '\uB85C\uADF8\uC778\uC2E4\uD328' | '\uD68C\uC6D0\uAC00\uC785\uD544\uC694';

  /**
   * 소셜 로그인 토큰
   */
  token: string | null;

  /**
   * 소셜 로그인 회원
   */
  user: UserDto | null;
}
