/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OauthCreateDto } from '../models/oauth-create-dto';
export interface OAuthConnectDto {
  oAuth: OauthCreateDto;
  token?: string;
}
