/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageInfoDto } from '../models/page-info-dto';
export interface OffsetPaginationDto {
  items: Array<Array<any>>;
  pageInfo: PageInfoDto;
}
