/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OpenApiSyncLogDto {
  apiCalls: number;
  createdAt: string;
  duration: number;
  entries: number;
  id: string;
  type: {
};
  updatedAt: string;
}
