/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface PolicyDto {

  /**
   * 작성자
   */
  admin: UserDto;

  /**
   * 작성자 ID
   */
  adminId: string;

  /**
   * 내용
   */
  content: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * 정책 ID
   */
  id: string;

  /**
   * 활성화 여부
   */
  isActive: boolean;

  /**
   * 제목
   */
  title: string;

  /**
   * 수정 일시
   */
  updatedAt: string;
}
