/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PolicyUpdateDto {

  /**
   * 내용
   */
  content?: string;

  /**
   * 활성화 여부
   */
  isActive?: boolean;

  /**
   * 제목
   */
  title?: string;
}
