/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PreStandardOpinionDto {
  '규격의견서파일URL': Array<string>;
  '답변번호': string;
  '사전규격등록번호': string;
  '의견내용': string;
  '의견번호': string;
  '의견제목': string;
  '입력일시': string;
  '작성업체명': string;
  '작성자명': string;
  '작성자이메일': string;
  '작성자전화번호': string;
  '참조번호': string;
}
