/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PreStandardOpinionDto } from '../models/pre-standard-opinion-dto';
export interface PreStandardDto {

  /**
   * SW사업대상여부
   */
  'SW사업대상여부': boolean;

  /**
   * 생성일
   */
  createdAt: string;

  /**
   * ID
   */
  id: string;

  /**
   * 키워드
   */
  keywords: Array<string>;

  /**
   * 규격문서파일URL
   */
  '규격문서파일URL': Array<string>;

  /**
   * 납품기한일시
   */
  '납품기한일시'?: string;

  /**
   * 납품일수
   */
  '납품일수'?: number;

  /**
   * 담당자명
   */
  '담당자명': string;

  /**
   * 담당자전화번호
   */
  '담당자전화번호': string;

  /**
   * 등록일시
   */
  '등록일시': string;

  /**
   * 물품상세목록
   */
  '물품상세목록': Array<string>;

  /**
   * 발주기관명
   */
  '발주기관명': string;

  /**
   * 배정예산금액
   */
  '배정예산금액': string;

  /**
   * 사전규격등록번호
   */
  '사전규격등록번호': string;

  /**
   * 실수요기관명
   */
  '실수요기관명': string;

  /**
   * 업무구분명
   */
  '업무구분명': string;

  /**
   * 의견등록마감일시
   */
  '의견등록마감일시': string;

  /**
   * 의견목록
   */
  '의견목록': Array<PreStandardOpinionDto>;

  /**
   * 입찰공고번호목록
   */
  '입찰공고번호목록': Array<string>;

  /**
   * 접수일시
   */
  '접수일시': string;

  /**
   * 참조번호
   */
  '참조번호': string;

  /**
   * 품명
   */
  '품명': string;
}
