/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RequestVisitorDto {

  /**
   * 도시
   */
  city: string;

  /**
   * IPv4
   */
  ip: string;

  /**
   * 국가
   */
  nation: string;

  /**
   * 접속 페이지
   */
  pageUrl: string;

  /**
   * 유입 경로
   */
  referrer: string;
}
