/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleLevelPermissionDto } from '../models/role-level-permission-dto';
export interface RoleDto {

  /**
   * 기본 여부
   */
  default: boolean;

  /**
   * 설명
   */
  description: string;

  /**
   * ID
   */
  id: string;

  /**
   * 이름
   */
  name: string;

  /**
   * 권한
   */
  permissions: Array<RoleLevelPermissionDto>;
}
