/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignInDto {

  /**
   * 이메일
   */
  email: string;

  /**
   * 비밀번호
   */
  password: string;
}
