/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatisticBidDto } from '../models/statistic-bid-dto';
import { StatisticUserDto } from '../models/statistic-user-dto';
export interface StatisticDto {

  /**
   * 조달 통계
   */
  bid: StatisticBidDto;

  /**
   * 가입 회원 통계
   */
  user: StatisticUserDto;
}
