/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StatisticBidDto {

  /**
   * 입찰 공고 수
   */
  notices: number;

  /**
   * 발주 계획 수
   */
  plans: number;

  /**
   * 사전 규격 수
   */
  specs: number;
}
