/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OauthCreateDto } from '../models/oauth-create-dto';
export interface UpdateUserDto {

  /**
   * 약관 전체 동의 여부
   */
  agreementAll?: boolean;

  /**
   * 약관 1 동의 여부
   */
  agreementTerm1?: boolean;

  /**
   * 약관 2 동의 여부
   */
  agreementTerm2?: boolean;

  /**
   * 사용자 연락처
   */
  contact?: string;

  /**
   * 사용자 이메일
   */
  email?: string;

  /**
   * 이메일 수신 동의 여부
   */
  emailConsent?: boolean;

  /**
   * 사용자 이름
   */
  name?: string;

  /**
   * 사용자 닉네임
   */
  nickname?: string;

  /**
   * SNS 정보
   */
  oAuth?: OauthCreateDto;

  /**
   * 권한 ID
   */
  permissionId?: string;

  /**
   * SMS 수신 동의 여부
   */
  smsConsent?: boolean;
}
