/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateInquiryDto {

  /**
   * 문의 답변
   */
  answer?: string | null;

  /**
   * 문의 내용
   */
  content?: string;

  /**
   * 문의 제목
   */
  title?: string;
}
