/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateAdminDto {

  /**
   * 이메일 주소
   */
  email?: string;

  /**
   * 관리자명
   */
  name?: string;

  /**
   * 비밀번호
   */
  password?: string;

  /**
   * 비밀번호 확인
   */
  passwordConfirm?: string;
}
