/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VisitorDeviceTypeDto } from '../models/visitor-device-type-dto';
export interface VisitorChartDataDto {

  /**
   * 브라우저
   */
  browsers: VisitorDeviceTypeDto;

  /**
   * 방문자 수
   */
  counts: Array<number>;

  /**
   * 날짜
   */
  dates: Array<string>;

  /**
   * 기기
   */
  devices: VisitorDeviceTypeDto;

  /**
   * OS
   */
  oses: VisitorDeviceTypeDto;

  /**
   * 접속 페이지
   */
  pageUrls: Array<string>;

  /**
   * 유입 페이지
   */
  referrers: Array<string>;
}
