/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BookmarkDto } from '../../models/bookmark-dto';

export interface BookmarkControllerFindMy$Params {
}

export function bookmarkControllerFindMy(http: HttpClient, rootUrl: string, params?: BookmarkControllerFindMy$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookmarkDto>>> {
  const rb = new RequestBuilder(rootUrl, bookmarkControllerFindMy.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BookmarkDto>>;
    })
  );
}

bookmarkControllerFindMy.PATH = '/api/bookmark/my';
