/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BidViewDto } from '../../models/bid-view-dto';
import { OffsetPaginationDto } from '../../models/offset-pagination-dto';

export interface BidControllerGetBookmarked$Params {

/**
 * 페이지 크기
 */
  pageSize: number;

/**
 * 정렬 기준
 */
  orderBy?: string;

/**
 * 정렬 방향
 */
  align?: 'asc' | 'desc';

/**
 * 검색어
 */
  query?: string;

/**
 * 페이지 번호
 */
  pageNo: number;
  startDate?: string;
  endDate?: string;
  '담당자'?: string;
  keywords?: Array<string>;
  andKeywords?: Array<string>;
  orKeywords?: Array<string>;
  notKeywords?: Array<string>;
  '공고기관'?: string;
  '수요기관'?: string;
  '입찰개시일시시작'?: string;
  '입찰개시일시종료'?: string;
  budgetStartPrice?: string;
  budgetEndPrice?: string;
  type?: 'service' | 'thing' | 'construction' | 'foreign';
  '모의공고여부'?: boolean;
}

export function bidControllerGetBookmarked(http: HttpClient, rootUrl: string, params: BidControllerGetBookmarked$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
}>> {
  const rb = new RequestBuilder(rootUrl, bidControllerGetBookmarked.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('align', params.align, {});
    rb.query('query', params.query, {});
    rb.query('pageNo', params.pageNo, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('담당자', params['담당자'], {});
    rb.query('keywords', params.keywords, {});
    rb.query('andKeywords', params.andKeywords, {});
    rb.query('orKeywords', params.orKeywords, {});
    rb.query('notKeywords', params.notKeywords, {});
    rb.query('공고기관', params['공고기관'], {});
    rb.query('수요기관', params['수요기관'], {});
    rb.query('입찰개시일시시작', params['입찰개시일시시작'], {});
    rb.query('입찰개시일시종료', params['입찰개시일시종료'], {});
    rb.query('budgetStartPrice', params.budgetStartPrice, {});
    rb.query('budgetEndPrice', params.budgetEndPrice, {});
    rb.query('type', params.type, {});
    rb.query('모의공고여부', params['모의공고여부'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OffsetPaginationDto & {
      'items'?: Array<BidViewDto>;
      }>;
    })
  );
}

bidControllerGetBookmarked.PATH = '/api/bid/bookmark';
