/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { MenuService } from './services/menu.service';
import { UserService } from './services/user.service';
import { UserRoleService } from './services/user-role.service';
import { OAuthService } from './services/o-auth.service';
import { GoogleService } from './services/google.service';
import { KakaoService } from './services/kakao.service';
import { StorageService } from './services/storage.service';
import { SettingService } from './services/setting.service';
import { InquiryService } from './services/inquiry.service';
import { FaqService } from './services/faq.service';
import { NoticeService } from './services/notice.service';
import { HealthService } from './services/health.service';
import { VisitorService } from './services/visitor.service';
import { UserManagementService } from './services/user-management.service';
import { AdminService } from './services/admin.service';
import { PolicyService } from './services/policy.service';
import { BusinessInfoService } from './services/business-info.service';
import { BannerService } from './services/banner.service';
import { StatisticsService } from './services/statistics.service';
import { LogService } from './services/log.service';
import { OrderPlanService } from './services/order-plan.service';
import { BidService } from './services/bid.service';
import { PreStandardService } from './services/pre-standard.service';
import { BookmarkService } from './services/bookmark.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    MenuService,
    UserService,
    UserRoleService,
    OAuthService,
    GoogleService,
    KakaoService,
    StorageService,
    SettingService,
    InquiryService,
    FaqService,
    NoticeService,
    HealthService,
    VisitorService,
    UserManagementService,
    AdminService,
    PolicyService,
    BusinessInfoService,
    BannerService,
    StatisticsService,
    LogService,
    OrderPlanService,
    BidService,
    PreStandardService,
    BookmarkService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
