/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BannerSearchResponseDto } from '../../models/banner-search-response-dto';

export interface BannerControllerSearch$Params {

/**
 * 페이지 크기
 */
  pageSize: number;

/**
 * 정렬 기준
 */
  orderBy?: string;

/**
 * 정렬 방향
 */
  align?: 'asc' | 'desc';

/**
 * 검색어
 */
  query?: string;

/**
 * 페이지 번호
 */
  pageNo: number;

/**
 * 노출 여부
 */
  isExposed?: boolean;

/**
 * 생성 시작일시
 */
  startCreatedAt?: string;

/**
 * 생성 종료일시
 */
  endCreatedAt?: string;

/**
 * 모드(웹용/모바일용)
 */
  mode?: string;
}

export function bannerControllerSearch(http: HttpClient, rootUrl: string, params: BannerControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<BannerSearchResponseDto>> {
  const rb = new RequestBuilder(rootUrl, bannerControllerSearch.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('align', params.align, {});
    rb.query('query', params.query, {});
    rb.query('pageNo', params.pageNo, {});
    rb.query('isExposed', params.isExposed, {});
    rb.query('startCreatedAt', params.startCreatedAt, {});
    rb.query('endCreatedAt', params.endCreatedAt, {});
    rb.query('mode', params.mode, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BannerSearchResponseDto>;
    })
  );
}

bannerControllerSearch.PATH = '/api/banner';
