/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuPermissionDto } from '../../models/menu-permission-dto';

export interface MenuControllerDeletePermission$Params {
  permissionId: string;
}

export function menuControllerDeletePermission(http: HttpClient, rootUrl: string, params: MenuControllerDeletePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuPermissionDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerDeletePermission.PATH, 'delete');
  if (params) {
    rb.path('permissionId', params.permissionId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuPermissionDto>;
    })
  );
}

menuControllerDeletePermission.PATH = '/api/menu/permission/{permissionId}';
