/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMenuPermissionDto } from '../../models/create-menu-permission-dto';
import { MenuPermissionDto } from '../../models/menu-permission-dto';

export interface MenuControllerUpdatePermission$Params {
  permissionId: string;
      body: CreateMenuPermissionDto
}

export function menuControllerUpdatePermission(http: HttpClient, rootUrl: string, params: MenuControllerUpdatePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuPermissionDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerUpdatePermission.PATH, 'patch');
  if (params) {
    rb.path('permissionId', params.permissionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuPermissionDto>;
    })
  );
}

menuControllerUpdatePermission.PATH = '/api/menu/permission/{permissionId}';
