/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PolicyDto } from '../../models/policy-dto';

export interface PolicyControllerFindByTitle$Params {
  title: string;
}

export function policyControllerFindByTitle(http: HttpClient, rootUrl: string, params: PolicyControllerFindByTitle$Params, context?: HttpContext): Observable<StrictHttpResponse<PolicyDto>> {
  const rb = new RequestBuilder(rootUrl, policyControllerFindByTitle.PATH, 'get');
  if (params) {
    rb.path('title', params.title, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PolicyDto>;
    })
  );
}

policyControllerFindByTitle.PATH = '/api/policy/{title}';
