/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OffsetPaginationDto } from '../../models/offset-pagination-dto';
import { OrderPlanDto } from '../../models/order-plan-dto';

export interface OrderPlanControllerGetBookmarked$Params {

/**
 * 페이지 크기
 */
  pageSize: number;

/**
 * 정렬 기준
 */
  orderBy?: string;

/**
 * 정렬 방향
 */
  align?: 'asc' | 'desc';

/**
 * 검색어
 */
  query?: string;

/**
 * 페이지 번호
 */
  pageNo: number;
  startDate?: string;
  endDate?: string;
  '담당자'?: string;
  keywords?: Array<string>;
  andKeywords?: Array<string>;
  orKeywords?: Array<string>;
  notKeywords?: Array<string>;
  '발주기관'?: string;
  startPrice?: string;
  endPrice?: string;
  type?: '\uC77C\uBC18\uC6A9\uC5ED' | '\uAE30\uC220\uC6A9\uC5ED' | '\uBB3C\uD488' | '\uACF5\uC0AC' | '\uC678\uC790';
}

export function orderPlanControllerGetBookmarked(http: HttpClient, rootUrl: string, params: OrderPlanControllerGetBookmarked$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
}>> {
  const rb = new RequestBuilder(rootUrl, orderPlanControllerGetBookmarked.PATH, 'get');
  if (params) {
    rb.query('pageSize', params.pageSize, {});
    rb.query('orderBy', params.orderBy, {});
    rb.query('align', params.align, {});
    rb.query('query', params.query, {});
    rb.query('pageNo', params.pageNo, {});
    rb.query('startDate', params.startDate, {});
    rb.query('endDate', params.endDate, {});
    rb.query('담당자', params['담당자'], {});
    rb.query('keywords', params.keywords, {});
    rb.query('andKeywords', params.andKeywords, {});
    rb.query('orKeywords', params.orKeywords, {});
    rb.query('notKeywords', params.notKeywords, {});
    rb.query('발주기관', params['발주기관'], {});
    rb.query('startPrice', params.startPrice, {});
    rb.query('endPrice', params.endPrice, {});
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OffsetPaginationDto & {
      'items'?: Array<OrderPlanDto>;
      }>;
    })
  );
}

orderPlanControllerGetBookmarked.PATH = '/api/order-plan/bookmark';
