/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BidConstructionDto } from '../models/bid-construction-dto';
import { bidControllerDownload } from '../fn/bid/bid-controller-download';
import { BidControllerDownload$Params } from '../fn/bid/bid-controller-download';
import { bidControllerFindById } from '../fn/bid/bid-controller-find-by-id';
import { BidControllerFindById$Params } from '../fn/bid/bid-controller-find-by-id';
import { bidControllerGetBookmarked } from '../fn/bid/bid-controller-get-bookmarked';
import { BidControllerGetBookmarked$Params } from '../fn/bid/bid-controller-get-bookmarked';
import { bidControllerGetLatestLog } from '../fn/bid/bid-controller-get-latest-log';
import { BidControllerGetLatestLog$Params } from '../fn/bid/bid-controller-get-latest-log';
import { bidControllerSearch } from '../fn/bid/bid-controller-search';
import { BidControllerSearch$Params } from '../fn/bid/bid-controller-search';
import { bidControllerSync } from '../fn/bid/bid-controller-sync';
import { BidControllerSync$Params } from '../fn/bid/bid-controller-sync';
import { bidControllerUpdateKeywords } from '../fn/bid/bid-controller-update-keywords';
import { BidControllerUpdateKeywords$Params } from '../fn/bid/bid-controller-update-keywords';
import { BidForeignDto } from '../models/bid-foreign-dto';
import { BidServiceDto } from '../models/bid-service-dto';
import { BidThingDto } from '../models/bid-thing-dto';
import { BidViewDto } from '../models/bid-view-dto';
import { OffsetPaginationDto } from '../models/offset-pagination-dto';
import { OpenApiSyncLogDto } from '../models/open-api-sync-log-dto';

@Injectable({ providedIn: 'root' })
export class BidService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `bidControllerSearch()` */
  static readonly BidControllerSearchPath = '/api/bid/search';

  /**
   * 입찰공고 검색.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bidControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerSearch$Response(params: BidControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
}>> {
    return bidControllerSearch(this.http, this.rootUrl, params, context);
  }

  /**
   * 입찰공고 검색.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bidControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerSearch(params: BidControllerSearch$Params, context?: HttpContext): Observable<OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
}> {
    return this.bidControllerSearch$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
}>): OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
} => r.body)
    );
  }

  /** Path part for operation `bidControllerGetBookmarked()` */
  static readonly BidControllerGetBookmarkedPath = '/api/bid/bookmark';

  /**
   * 즐겨찾기한 발주계획 검색.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bidControllerGetBookmarked()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerGetBookmarked$Response(params: BidControllerGetBookmarked$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
}>> {
    return bidControllerGetBookmarked(this.http, this.rootUrl, params, context);
  }

  /**
   * 즐겨찾기한 발주계획 검색.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bidControllerGetBookmarked$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerGetBookmarked(params: BidControllerGetBookmarked$Params, context?: HttpContext): Observable<OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
}> {
    return this.bidControllerGetBookmarked$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
}>): OffsetPaginationDto & {
'items'?: Array<BidViewDto>;
} => r.body)
    );
  }

  /** Path part for operation `bidControllerFindById()` */
  static readonly BidControllerFindByIdPath = '/api/bid/{id}';

  /**
   * 입찰공고 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bidControllerFindById()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerFindById$Response(params: BidControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<(BidConstructionDto | BidForeignDto | BidServiceDto | BidThingDto)>> {
    return bidControllerFindById(this.http, this.rootUrl, params, context);
  }

  /**
   * 입찰공고 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bidControllerFindById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerFindById(params: BidControllerFindById$Params, context?: HttpContext): Observable<(BidConstructionDto | BidForeignDto | BidServiceDto | BidThingDto)> {
    return this.bidControllerFindById$Response(params, context).pipe(
      map((r: StrictHttpResponse<(BidConstructionDto | BidForeignDto | BidServiceDto | BidThingDto)>): (BidConstructionDto | BidForeignDto | BidServiceDto | BidThingDto) => r.body)
    );
  }

  /** Path part for operation `bidControllerGetLatestLog()` */
  static readonly BidControllerGetLatestLogPath = '/api/bid/log/latest';

  /**
   * 최근 동기화 로그 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bidControllerGetLatestLog()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerGetLatestLog$Response(params?: BidControllerGetLatestLog$Params, context?: HttpContext): Observable<StrictHttpResponse<OpenApiSyncLogDto>> {
    return bidControllerGetLatestLog(this.http, this.rootUrl, params, context);
  }

  /**
   * 최근 동기화 로그 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bidControllerGetLatestLog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerGetLatestLog(params?: BidControllerGetLatestLog$Params, context?: HttpContext): Observable<OpenApiSyncLogDto> {
    return this.bidControllerGetLatestLog$Response(params, context).pipe(
      map((r: StrictHttpResponse<OpenApiSyncLogDto>): OpenApiSyncLogDto => r.body)
    );
  }

  /** Path part for operation `bidControllerSync()` */
  static readonly BidControllerSyncPath = '/api/bid/sync';

  /**
   * 입찰공고 동기화.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bidControllerSync()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerSync$Response(params?: BidControllerSync$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bidControllerSync(this.http, this.rootUrl, params, context);
  }

  /**
   * 입찰공고 동기화.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bidControllerSync$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bidControllerSync(params?: BidControllerSync$Params, context?: HttpContext): Observable<void> {
    return this.bidControllerSync$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `bidControllerDownload()` */
  static readonly BidControllerDownloadPath = '/api/bid/download';

  /**
   * 입찰공고 파일 다운로드.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bidControllerDownload()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bidControllerDownload$Response(params: BidControllerDownload$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return bidControllerDownload(this.http, this.rootUrl, params, context);
  }

  /**
   * 입찰공고 파일 다운로드.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bidControllerDownload$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bidControllerDownload(params: BidControllerDownload$Params, context?: HttpContext): Observable<Blob> {
    return this.bidControllerDownload$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `bidControllerUpdateKeywords()` */
  static readonly BidControllerUpdateKeywordsPath = '/api/bid/{id}/keywords';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bidControllerUpdateKeywords()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bidControllerUpdateKeywords$Response(params: BidControllerUpdateKeywords$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return bidControllerUpdateKeywords(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bidControllerUpdateKeywords$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bidControllerUpdateKeywords(params: BidControllerUpdateKeywords$Params, context?: HttpContext): Observable<void> {
    return this.bidControllerUpdateKeywords$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
