/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { bookmarkControllerFindMy } from '../fn/bookmark/bookmark-controller-find-my';
import { BookmarkControllerFindMy$Params } from '../fn/bookmark/bookmark-controller-find-my';
import { bookmarkControllerToggle } from '../fn/bookmark/bookmark-controller-toggle';
import { BookmarkControllerToggle$Params } from '../fn/bookmark/bookmark-controller-toggle';
import { BookmarkDto } from '../models/bookmark-dto';

@Injectable({ providedIn: 'root' })
export class BookmarkService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `bookmarkControllerFindMy()` */
  static readonly BookmarkControllerFindMyPath = '/api/bookmark/my';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerFindMy()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerFindMy$Response(params?: BookmarkControllerFindMy$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BookmarkDto>>> {
    return bookmarkControllerFindMy(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerFindMy$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  bookmarkControllerFindMy(params?: BookmarkControllerFindMy$Params, context?: HttpContext): Observable<Array<BookmarkDto>> {
    return this.bookmarkControllerFindMy$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<BookmarkDto>>): Array<BookmarkDto> => r.body)
    );
  }

  /** Path part for operation `bookmarkControllerToggle()` */
  static readonly BookmarkControllerTogglePath = '/api/bookmark';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `bookmarkControllerToggle()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bookmarkControllerToggle$Response(params: BookmarkControllerToggle$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return bookmarkControllerToggle(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `bookmarkControllerToggle$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  bookmarkControllerToggle(params: BookmarkControllerToggle$Params, context?: HttpContext): Observable<boolean> {
    return this.bookmarkControllerToggle$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
