/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { businessInfoControllerCreate } from '../fn/business-info/business-info-controller-create';
import { BusinessInfoControllerCreate$Params } from '../fn/business-info/business-info-controller-create';
import { businessInfoControllerGetBusinessInfo } from '../fn/business-info/business-info-controller-get-business-info';
import { BusinessInfoControllerGetBusinessInfo$Params } from '../fn/business-info/business-info-controller-get-business-info';
import { businessInfoControllerUpdate } from '../fn/business-info/business-info-controller-update';
import { BusinessInfoControllerUpdate$Params } from '../fn/business-info/business-info-controller-update';
import { BusinessInfoDto } from '../models/business-info-dto';

@Injectable({ providedIn: 'root' })
export class BusinessInfoService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `businessInfoControllerGetBusinessInfo()` */
  static readonly BusinessInfoControllerGetBusinessInfoPath = '/api/business-info';

  /**
   * 사업자 정보 관리 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `businessInfoControllerGetBusinessInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  businessInfoControllerGetBusinessInfo$Response(params?: BusinessInfoControllerGetBusinessInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<BusinessInfoDto>> {
    return businessInfoControllerGetBusinessInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * 사업자 정보 관리 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `businessInfoControllerGetBusinessInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  businessInfoControllerGetBusinessInfo(params?: BusinessInfoControllerGetBusinessInfo$Params, context?: HttpContext): Observable<BusinessInfoDto> {
    return this.businessInfoControllerGetBusinessInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<BusinessInfoDto>): BusinessInfoDto => r.body)
    );
  }

  /** Path part for operation `businessInfoControllerCreate()` */
  static readonly BusinessInfoControllerCreatePath = '/api/business-info';

  /**
   * 사업자 정보 관리 생성.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `businessInfoControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  businessInfoControllerCreate$Response(params: BusinessInfoControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return businessInfoControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * 사업자 정보 관리 생성.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `businessInfoControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  businessInfoControllerCreate(params: BusinessInfoControllerCreate$Params, context?: HttpContext): Observable<boolean> {
    return this.businessInfoControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `businessInfoControllerUpdate()` */
  static readonly BusinessInfoControllerUpdatePath = '/api/business-info';

  /**
   * 사업자 정보 관리 수정.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `businessInfoControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  businessInfoControllerUpdate$Response(params: BusinessInfoControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return businessInfoControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * 사업자 정보 관리 수정.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `businessInfoControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  businessInfoControllerUpdate(params: BusinessInfoControllerUpdate$Params, context?: HttpContext): Observable<boolean> {
    return this.businessInfoControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
