/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { statisticControllerFindStatistic } from '../fn/statistics/statistic-controller-find-statistic';
import { StatisticControllerFindStatistic$Params } from '../fn/statistics/statistic-controller-find-statistic';
import { statisticControllerGetSignUpUsersByDate } from '../fn/statistics/statistic-controller-get-sign-up-users-by-date';
import { StatisticControllerGetSignUpUsersByDate$Params } from '../fn/statistics/statistic-controller-get-sign-up-users-by-date';
import { StatisticDto } from '../models/statistic-dto';

@Injectable({ providedIn: 'root' })
export class StatisticsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `statisticControllerFindStatistic()` */
  static readonly StatisticControllerFindStatisticPath = '/api/statistics';

  /**
   * 통계 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `statisticControllerFindStatistic()` instead.
   *
   * This method doesn't expect any request body.
   */
  statisticControllerFindStatistic$Response(params?: StatisticControllerFindStatistic$Params, context?: HttpContext): Observable<StrictHttpResponse<StatisticDto>> {
    return statisticControllerFindStatistic(this.http, this.rootUrl, params, context);
  }

  /**
   * 통계 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `statisticControllerFindStatistic$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  statisticControllerFindStatistic(params?: StatisticControllerFindStatistic$Params, context?: HttpContext): Observable<StatisticDto> {
    return this.statisticControllerFindStatistic$Response(params, context).pipe(
      map((r: StrictHttpResponse<StatisticDto>): StatisticDto => r.body)
    );
  }

  /** Path part for operation `statisticControllerGetSignUpUsersByDate()` */
  static readonly StatisticControllerGetSignUpUsersByDatePath = '/api/statistics/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `statisticControllerGetSignUpUsersByDate()` instead.
   *
   * This method doesn't expect any request body.
   */
  statisticControllerGetSignUpUsersByDate$Response(params: StatisticControllerGetSignUpUsersByDate$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Array<number>>>> {
    return statisticControllerGetSignUpUsersByDate(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `statisticControllerGetSignUpUsersByDate$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  statisticControllerGetSignUpUsersByDate(params: StatisticControllerGetSignUpUsersByDate$Params, context?: HttpContext): Observable<Array<Array<number>>> {
    return this.statisticControllerGetSignUpUsersByDate$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Array<number>>>): Array<Array<number>> => r.body)
    );
  }

}
