/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { FindEmailResponseDto } from '../models/find-email-response-dto';
import { OffsetPaginationDto } from '../models/offset-pagination-dto';
import { TokenDto } from '../models/token-dto';
import { userControllerBlock } from '../fn/user/user-controller-block';
import { UserControllerBlock$Params } from '../fn/user/user-controller-block';
import { userControllerCheckContact } from '../fn/user/user-controller-check-contact';
import { UserControllerCheckContact$Params } from '../fn/user/user-controller-check-contact';
import { userControllerCheckEmail } from '../fn/user/user-controller-check-email';
import { UserControllerCheckEmail$Params } from '../fn/user/user-controller-check-email';
import { userControllerCreate } from '../fn/user/user-controller-create';
import { UserControllerCreate$Params } from '../fn/user/user-controller-create';
import { userControllerDelete } from '../fn/user/user-controller-delete';
import { UserControllerDelete$Params } from '../fn/user/user-controller-delete';
import { userControllerDeleteMany } from '../fn/user/user-controller-delete-many';
import { UserControllerDeleteMany$Params } from '../fn/user/user-controller-delete-many';
import { userControllerFindById } from '../fn/user/user-controller-find-by-id';
import { UserControllerFindById$Params } from '../fn/user/user-controller-find-by-id';
import { userControllerFindEmail } from '../fn/user/user-controller-find-email';
import { UserControllerFindEmail$Params } from '../fn/user/user-controller-find-email';
import { userControllerGetAccessTokenByContact } from '../fn/user/user-controller-get-access-token-by-contact';
import { UserControllerGetAccessTokenByContact$Params } from '../fn/user/user-controller-get-access-token-by-contact';
import { userControllerGetAccessTokenByEmail } from '../fn/user/user-controller-get-access-token-by-email';
import { UserControllerGetAccessTokenByEmail$Params } from '../fn/user/user-controller-get-access-token-by-email';
import { userControllerGetMe } from '../fn/user/user-controller-get-me';
import { UserControllerGetMe$Params } from '../fn/user/user-controller-get-me';
import { userControllerLogout } from '../fn/user/user-controller-logout';
import { UserControllerLogout$Params } from '../fn/user/user-controller-logout';
import { userControllerRefresh } from '../fn/user/user-controller-refresh';
import { UserControllerRefresh$Params } from '../fn/user/user-controller-refresh';
import { userControllerResetPassword } from '../fn/user/user-controller-reset-password';
import { UserControllerResetPassword$Params } from '../fn/user/user-controller-reset-password';
import { userControllerSearch } from '../fn/user/user-controller-search';
import { UserControllerSearch$Params } from '../fn/user/user-controller-search';
import { userControllerSendCode } from '../fn/user/user-controller-send-code';
import { UserControllerSendCode$Params } from '../fn/user/user-controller-send-code';
import { userControllerSendEmailCode } from '../fn/user/user-controller-send-email-code';
import { UserControllerSendEmailCode$Params } from '../fn/user/user-controller-send-email-code';
import { userControllerSendPasswordResetEmail } from '../fn/user/user-controller-send-password-reset-email';
import { UserControllerSendPasswordResetEmail$Params } from '../fn/user/user-controller-send-password-reset-email';
import { userControllerSigninWithEmail } from '../fn/user/user-controller-signin-with-email';
import { UserControllerSigninWithEmail$Params } from '../fn/user/user-controller-signin-with-email';
import { userControllerSigninWithSns } from '../fn/user/user-controller-signin-with-sns';
import { UserControllerSigninWithSns$Params } from '../fn/user/user-controller-signin-with-sns';
import { userControllerSignUpWithSns } from '../fn/user/user-controller-sign-up-with-sns';
import { UserControllerSignUpWithSns$Params } from '../fn/user/user-controller-sign-up-with-sns';
import { userControllerToggleBlock } from '../fn/user/user-controller-toggle-block';
import { UserControllerToggleBlock$Params } from '../fn/user/user-controller-toggle-block';
import { userControllerUnblock } from '../fn/user/user-controller-unblock';
import { UserControllerUnblock$Params } from '../fn/user/user-controller-unblock';
import { userControllerUnwithdraw } from '../fn/user/user-controller-unwithdraw';
import { UserControllerUnwithdraw$Params } from '../fn/user/user-controller-unwithdraw';
import { userControllerUpdate } from '../fn/user/user-controller-update';
import { UserControllerUpdate$Params } from '../fn/user/user-controller-update';
import { userControllerUpdateContact } from '../fn/user/user-controller-update-contact';
import { UserControllerUpdateContact$Params } from '../fn/user/user-controller-update-contact';
import { userControllerUpdatePassword } from '../fn/user/user-controller-update-password';
import { UserControllerUpdatePassword$Params } from '../fn/user/user-controller-update-password';
import { userControllerVerifyCode } from '../fn/user/user-controller-verify-code';
import { UserControllerVerifyCode$Params } from '../fn/user/user-controller-verify-code';
import { userControllerVerifyEmailCode } from '../fn/user/user-controller-verify-email-code';
import { UserControllerVerifyEmailCode$Params } from '../fn/user/user-controller-verify-email-code';
import { userControllerWithdraw } from '../fn/user/user-controller-withdraw';
import { UserControllerWithdraw$Params } from '../fn/user/user-controller-withdraw';
import { UserDto } from '../models/user-dto';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userControllerCheckEmail()` */
  static readonly UserControllerCheckEmailPath = '/api/user/check/email';

  /**
   * 이메일 중복 확인.
   *
   * 이메일 중복을 확인합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerCheckEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerCheckEmail$Response(params: UserControllerCheckEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerCheckEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * 이메일 중복 확인.
   *
   * 이메일 중복을 확인합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerCheckEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerCheckEmail(params: UserControllerCheckEmail$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerCheckEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerCheckContact()` */
  static readonly UserControllerCheckContactPath = '/api/user/check/contact';

  /**
   * 연락처 중복 확인.
   *
   * 연락처 중복을 확인합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerCheckContact()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerCheckContact$Response(params: UserControllerCheckContact$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerCheckContact(this.http, this.rootUrl, params, context);
  }

  /**
   * 연락처 중복 확인.
   *
   * 연락처 중복을 확인합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerCheckContact$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerCheckContact(params: UserControllerCheckContact$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerCheckContact$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerGetMe()` */
  static readonly UserControllerGetMePath = '/api/user/me';

  /**
   * 내 정보 조회.
   *
   * 내 정보를 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerGetMe()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetMe$Response(params?: UserControllerGetMe$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userControllerGetMe(this.http, this.rootUrl, params, context);
  }

  /**
   * 내 정보 조회.
   *
   * 내 정보를 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerGetMe$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetMe(params?: UserControllerGetMe$Params, context?: HttpContext): Observable<UserDto> {
    return this.userControllerGetMe$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userControllerSearch()` */
  static readonly UserControllerSearchPath = '/api/user/search';

  /**
   * 사용자 검색.
   *
   * 사용자를 검색합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerSearch$Response(params: UserControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<UserDto>;
}>> {
    return userControllerSearch(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 검색.
   *
   * 사용자를 검색합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerSearch(params: UserControllerSearch$Params, context?: HttpContext): Observable<OffsetPaginationDto & {
'items'?: Array<UserDto>;
}> {
    return this.userControllerSearch$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<UserDto>;
}>): OffsetPaginationDto & {
'items'?: Array<UserDto>;
} => r.body)
    );
  }

  /** Path part for operation `userControllerGetAccessTokenByContact()` */
  static readonly UserControllerGetAccessTokenByContactPath = '/api/user/connect/contact';

  /**
   * 연락처 인증 후 계정 연결을 위해 연락처로 accessToken 발급.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerGetAccessTokenByContact()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAccessTokenByContact$Response(params: UserControllerGetAccessTokenByContact$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return userControllerGetAccessTokenByContact(this.http, this.rootUrl, params, context);
  }

  /**
   * 연락처 인증 후 계정 연결을 위해 연락처로 accessToken 발급.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerGetAccessTokenByContact$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAccessTokenByContact(params: UserControllerGetAccessTokenByContact$Params, context?: HttpContext): Observable<TokenDto> {
    return this.userControllerGetAccessTokenByContact$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `userControllerGetAccessTokenByEmail()` */
  static readonly UserControllerGetAccessTokenByEmailPath = '/api/user/connect/email';

  /**
   * 이메일 인증 후 계정 연결을 위해 이메일로 accessToken 발급.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerGetAccessTokenByEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAccessTokenByEmail$Response(params: UserControllerGetAccessTokenByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return userControllerGetAccessTokenByEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * 이메일 인증 후 계정 연결을 위해 이메일로 accessToken 발급.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerGetAccessTokenByEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerGetAccessTokenByEmail(params: UserControllerGetAccessTokenByEmail$Params, context?: HttpContext): Observable<TokenDto> {
    return this.userControllerGetAccessTokenByEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `userControllerFindById()` */
  static readonly UserControllerFindByIdPath = '/api/user/{id}';

  /**
   * 사용자 ID 기반 조회.
   *
   * 사용자를 ID 기반으로 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerFindById()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindById$Response(params: UserControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userControllerFindById(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 ID 기반 조회.
   *
   * 사용자를 ID 기반으로 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerFindById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerFindById(params: UserControllerFindById$Params, context?: HttpContext): Observable<UserDto> {
    return this.userControllerFindById$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userControllerDelete()` */
  static readonly UserControllerDeletePath = '/api/user/{id}';

  /**
   * 사용자 삭제.
   *
   * 사용자를 삭제합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerDelete$Response(params: UserControllerDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userControllerDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 삭제.
   *
   * 사용자를 삭제합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerDelete(params: UserControllerDelete$Params, context?: HttpContext): Observable<UserDto> {
    return this.userControllerDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userControllerFindEmail()` */
  static readonly UserControllerFindEmailPath = '/api/user/find/email';

  /**
   * 이메일 찾기.
   *
   * 사용자 연락처와 이름를 기반으로 해당 회원의 모든 이메일을 찾습니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerFindEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerFindEmail$Response(params: UserControllerFindEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FindEmailResponseDto>>> {
    return userControllerFindEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * 이메일 찾기.
   *
   * 사용자 연락처와 이름를 기반으로 해당 회원의 모든 이메일을 찾습니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerFindEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerFindEmail(params: UserControllerFindEmail$Params, context?: HttpContext): Observable<Array<FindEmailResponseDto>> {
    return this.userControllerFindEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FindEmailResponseDto>>): Array<FindEmailResponseDto> => r.body)
    );
  }

  /** Path part for operation `userControllerSendPasswordResetEmail()` */
  static readonly UserControllerSendPasswordResetEmailPath = '/api/user/find/password';

  /**
   * 비밀번호 재설정 인증 이메일 발송.
   *
   * 비밀번호 재설정 이메일을 발송합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerSendPasswordResetEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerSendPasswordResetEmail$Response(params: UserControllerSendPasswordResetEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerSendPasswordResetEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * 비밀번호 재설정 인증 이메일 발송.
   *
   * 비밀번호 재설정 이메일을 발송합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerSendPasswordResetEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerSendPasswordResetEmail(params: UserControllerSendPasswordResetEmail$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerSendPasswordResetEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerSigninWithEmail()` */
  static readonly UserControllerSigninWithEmailPath = '/api/user/signin';

  /**
   * email 사용자 로그인.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerSigninWithEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSigninWithEmail$Response(params: UserControllerSigninWithEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDto>> {
    return userControllerSigninWithEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * email 사용자 로그인.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerSigninWithEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSigninWithEmail(params: UserControllerSigninWithEmail$Params, context?: HttpContext): Observable<TokenDto> {
    return this.userControllerSigninWithEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<TokenDto>): TokenDto => r.body)
    );
  }

  /** Path part for operation `userControllerCreate()` */
  static readonly UserControllerCreatePath = '/api/user/signup';

  /**
   * 회원 가입.
   *
   * 회원으로 가입합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerCreate$Response(params: UserControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * 회원 가입.
   *
   * 회원으로 가입합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerCreate(params: UserControllerCreate$Params, context?: HttpContext): Observable<UserDto> {
    return this.userControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userControllerSignUpWithSns()` */
  static readonly UserControllerSignUpWithSnsPath = '/api/user/sns';

  /**
   * 최초 SNS 회원 가입.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerSignUpWithSns()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSignUpWithSns$Response(params: UserControllerSignUpWithSns$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userControllerSignUpWithSns(this.http, this.rootUrl, params, context);
  }

  /**
   * 최초 SNS 회원 가입.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerSignUpWithSns$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSignUpWithSns(params: UserControllerSignUpWithSns$Params, context?: HttpContext): Observable<UserDto> {
    return this.userControllerSignUpWithSns$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userControllerSigninWithSns()` */
  static readonly UserControllerSigninWithSnsPath = '/api/user/sns/signin';

  /**
   * SNS 계정 로그인.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerSigninWithSns()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSigninWithSns$Response(params: UserControllerSigninWithSns$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userControllerSigninWithSns(this.http, this.rootUrl, params, context);
  }

  /**
   * SNS 계정 로그인.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerSigninWithSns$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSigninWithSns(params: UserControllerSigninWithSns$Params, context?: HttpContext): Observable<UserDto> {
    return this.userControllerSigninWithSns$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userControllerRefresh()` */
  static readonly UserControllerRefreshPath = '/api/user/refresh';

  /**
   * 엑세스 토큰 갱신.
   *
   * 엑세스 토큰을 갱신합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerRefresh()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerRefresh$Response(params?: UserControllerRefresh$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'accessToken'?: string;
}>> {
    return userControllerRefresh(this.http, this.rootUrl, params, context);
  }

  /**
   * 엑세스 토큰 갱신.
   *
   * 엑세스 토큰을 갱신합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerRefresh$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerRefresh(params?: UserControllerRefresh$Params, context?: HttpContext): Observable<{
'accessToken'?: string;
}> {
    return this.userControllerRefresh$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'accessToken'?: string;
}>): {
'accessToken'?: string;
} => r.body)
    );
  }

  /** Path part for operation `userControllerLogout()` */
  static readonly UserControllerLogoutPath = '/api/user/signout';

  /**
   * 로그아웃.
   *
   * 로그아웃합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerLogout()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerLogout$Response(params?: UserControllerLogout$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerLogout(this.http, this.rootUrl, params, context);
  }

  /**
   * 로그아웃.
   *
   * 로그아웃합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerLogout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerLogout(params?: UserControllerLogout$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerLogout$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerSendCode()` */
  static readonly UserControllerSendCodePath = '/api/user/code';

  /**
   * 연락처 인증 코드 발송.
   *
   * 연락처로 인증을 요청합니다. 이름과 함께 요청하는 경우, 계정과 이름이 일치하는지 확인합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerSendCode()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSendCode$Response(params: UserControllerSendCode$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'token'?: string;
}>> {
    return userControllerSendCode(this.http, this.rootUrl, params, context);
  }

  /**
   * 연락처 인증 코드 발송.
   *
   * 연락처로 인증을 요청합니다. 이름과 함께 요청하는 경우, 계정과 이름이 일치하는지 확인합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerSendCode$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSendCode(params: UserControllerSendCode$Params, context?: HttpContext): Observable<{
'token'?: string;
}> {
    return this.userControllerSendCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'token'?: string;
}>): {
'token'?: string;
} => r.body)
    );
  }

  /** Path part for operation `userControllerVerifyCode()` */
  static readonly UserControllerVerifyCodePath = '/api/user/code/verify';

  /**
   * 연락처 인증 코드 확인.
   *
   * 연락처로 전송된 인증 코드를 확인합니다
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerVerifyCode()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerVerifyCode$Response(params: UserControllerVerifyCode$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerVerifyCode(this.http, this.rootUrl, params, context);
  }

  /**
   * 연락처 인증 코드 확인.
   *
   * 연락처로 전송된 인증 코드를 확인합니다
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerVerifyCode$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerVerifyCode(params: UserControllerVerifyCode$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerVerifyCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerSendEmailCode()` */
  static readonly UserControllerSendEmailCodePath = '/api/user/email';

  /**
   * 이메일 인증 코드 발송.
   *
   * 이메일로 인증 코드를 발송합니다. 이름과 함께 요청하는 경우, 계정과 이름이 일치하는지 확인합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerSendEmailCode()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSendEmailCode$Response(params: UserControllerSendEmailCode$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'token'?: string;
}>> {
    return userControllerSendEmailCode(this.http, this.rootUrl, params, context);
  }

  /**
   * 이메일 인증 코드 발송.
   *
   * 이메일로 인증 코드를 발송합니다. 이름과 함께 요청하는 경우, 계정과 이름이 일치하는지 확인합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerSendEmailCode$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerSendEmailCode(params: UserControllerSendEmailCode$Params, context?: HttpContext): Observable<{
'token'?: string;
}> {
    return this.userControllerSendEmailCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'token'?: string;
}>): {
'token'?: string;
} => r.body)
    );
  }

  /** Path part for operation `userControllerVerifyEmailCode()` */
  static readonly UserControllerVerifyEmailCodePath = '/api/user/email/verify';

  /**
   * 이메일 인증 코드 확인.
   *
   * 이메일로 전송된 인증 코드를 확인합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerVerifyEmailCode()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerVerifyEmailCode$Response(params: UserControllerVerifyEmailCode$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerVerifyEmailCode(this.http, this.rootUrl, params, context);
  }

  /**
   * 이메일 인증 코드 확인.
   *
   * 이메일로 전송된 인증 코드를 확인합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerVerifyEmailCode$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerVerifyEmailCode(params: UserControllerVerifyEmailCode$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerVerifyEmailCode$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerResetPassword()` */
  static readonly UserControllerResetPasswordPath = '/api/user/reset-password';

  /**
   * 토큰 기반 비밀번호 재설정.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerResetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerResetPassword$Response(params: UserControllerResetPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerResetPassword(this.http, this.rootUrl, params, context);
  }

  /**
   * 토큰 기반 비밀번호 재설정.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerResetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerResetPassword(params: UserControllerResetPassword$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerResetPassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerUpdatePassword()` */
  static readonly UserControllerUpdatePasswordPath = '/api/user/password';

  /**
   * 비밀번호 변경.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdatePassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdatePassword$Response(params: UserControllerUpdatePassword$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerUpdatePassword(this.http, this.rootUrl, params, context);
  }

  /**
   * 비밀번호 변경.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdatePassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdatePassword(params: UserControllerUpdatePassword$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerUpdatePassword$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerUpdateContact()` */
  static readonly UserControllerUpdateContactPath = '/api/user/contact';

  /**
   * 연락처 변경.
   *
   * 연락처를 변경합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdateContact()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdateContact$Response(params: UserControllerUpdateContact$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerUpdateContact(this.http, this.rootUrl, params, context);
  }

  /**
   * 연락처 변경.
   *
   * 연락처를 변경합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdateContact$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdateContact(params: UserControllerUpdateContact$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerUpdateContact$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerToggleBlock()` */
  static readonly UserControllerToggleBlockPath = '/api/user/{id}/status';

  /**
   * 회원 상태 변경.
   *
   * 회원의 상태를 활성화 또는 차단으로 변경합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerToggleBlock()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerToggleBlock$Response(params: UserControllerToggleBlock$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return userControllerToggleBlock(this.http, this.rootUrl, params, context);
  }

  /**
   * 회원 상태 변경.
   *
   * 회원의 상태를 활성화 또는 차단으로 변경합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerToggleBlock$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerToggleBlock(params: UserControllerToggleBlock$Params, context?: HttpContext): Observable<void> {
    return this.userControllerToggleBlock$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `userControllerDeleteMany()` */
  static readonly UserControllerDeleteManyPath = '/api/user';

  /**
   * 사용자 다중 삭제.
   *
   * 여러 사용자를 삭제합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerDeleteMany()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerDeleteMany$Response(params: UserControllerDeleteMany$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'count'?: number;
}>> {
    return userControllerDeleteMany(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 다중 삭제.
   *
   * 여러 사용자를 삭제합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerDeleteMany$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerDeleteMany(params: UserControllerDeleteMany$Params, context?: HttpContext): Observable<{
'count'?: number;
}> {
    return this.userControllerDeleteMany$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'count'?: number;
}>): {
'count'?: number;
} => r.body)
    );
  }

  /** Path part for operation `userControllerUpdate()` */
  static readonly UserControllerUpdatePath = '/api/user';

  /**
   * 사용자 정보 수정.
   *
   * 사용자 정보를 수정합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdate$Response(params: UserControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 정보 수정.
   *
   * 사용자 정보를 수정합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerUpdate(params: UserControllerUpdate$Params, context?: HttpContext): Observable<UserDto> {
    return this.userControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userControllerWithdraw()` */
  static readonly UserControllerWithdrawPath = '/api/user/withdraw';

  /**
   * 회원 탈퇴.
   *
   * 회원을 탈퇴 대기 상태(재가입 가능)로 변경합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerWithdraw()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerWithdraw$Response(params: UserControllerWithdraw$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerWithdraw(this.http, this.rootUrl, params, context);
  }

  /**
   * 회원 탈퇴.
   *
   * 회원을 탈퇴 대기 상태(재가입 가능)로 변경합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerWithdraw$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userControllerWithdraw(params: UserControllerWithdraw$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerWithdraw$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerUnwithdraw()` */
  static readonly UserControllerUnwithdrawPath = '/api/user/unwithdraw';

  /**
   * 회원 탈퇴 취소.
   *
   * 회원 탈퇴를 취소합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUnwithdraw()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerUnwithdraw$Response(params?: UserControllerUnwithdraw$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerUnwithdraw(this.http, this.rootUrl, params, context);
  }

  /**
   * 회원 탈퇴 취소.
   *
   * 회원 탈퇴를 취소합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUnwithdraw$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerUnwithdraw(params?: UserControllerUnwithdraw$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerUnwithdraw$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerBlock()` */
  static readonly UserControllerBlockPath = '/api/user/{id}/block';

  /**
   * 사용자 차단.
   *
   * 사용자를 차단합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerBlock()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerBlock$Response(params: UserControllerBlock$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerBlock(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 차단.
   *
   * 사용자를 차단합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerBlock$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerBlock(params: UserControllerBlock$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerBlock$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userControllerUnblock()` */
  static readonly UserControllerUnblockPath = '/api/user/{id}/unblock';

  /**
   * 사용자 차단 해제.
   *
   * 사용자의 차단을 해제합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userControllerUnblock()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerUnblock$Response(params: UserControllerUnblock$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userControllerUnblock(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 차단 해제.
   *
   * 사용자의 차단을 해제합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userControllerUnblock$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userControllerUnblock(params: UserControllerUnblock$Params, context?: HttpContext): Observable<boolean> {
    return this.userControllerUnblock$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
