/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CursorPaginationDto } from '../models/cursor-pagination-dto';
import { OffsetPaginationDto } from '../models/offset-pagination-dto';
import { UserDto } from '../models/user-dto';
import { userManagementControllerCreateV1 } from '../fn/user-management/user-management-controller-create-v-1';
import { UserManagementControllerCreateV1$Params } from '../fn/user-management/user-management-controller-create-v-1';
import { userManagementControllerFindByIdV1 } from '../fn/user-management/user-management-controller-find-by-id-v-1';
import { UserManagementControllerFindByIdV1$Params } from '../fn/user-management/user-management-controller-find-by-id-v-1';
import { userManagementControllerRemoveV1 } from '../fn/user-management/user-management-controller-remove-v-1';
import { UserManagementControllerRemoveV1$Params } from '../fn/user-management/user-management-controller-remove-v-1';
import { userManagementControllerSearchCursorV1 } from '../fn/user-management/user-management-controller-search-cursor-v-1';
import { UserManagementControllerSearchCursorV1$Params } from '../fn/user-management/user-management-controller-search-cursor-v-1';
import { userManagementControllerSearchOffsetV1 } from '../fn/user-management/user-management-controller-search-offset-v-1';
import { UserManagementControllerSearchOffsetV1$Params } from '../fn/user-management/user-management-controller-search-offset-v-1';
import { userManagementControllerUpdateV1 } from '../fn/user-management/user-management-controller-update-v-1';
import { UserManagementControllerUpdateV1$Params } from '../fn/user-management/user-management-controller-update-v-1';

@Injectable({ providedIn: 'root' })
export class UserManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userManagementControllerSearchOffsetV1()` */
  static readonly UserManagementControllerSearchOffsetV1Path = '/api/v1/user-management/search/offset';

  /**
   * 사용자 오프셋 기반 조회.
   *
   * 사용자를 오프셋 기반으로 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userManagementControllerSearchOffsetV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerSearchOffsetV1$Response(params?: UserManagementControllerSearchOffsetV1$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto>> {
    return userManagementControllerSearchOffsetV1(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 오프셋 기반 조회.
   *
   * 사용자를 오프셋 기반으로 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userManagementControllerSearchOffsetV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerSearchOffsetV1(params?: UserManagementControllerSearchOffsetV1$Params, context?: HttpContext): Observable<OffsetPaginationDto> {
    return this.userManagementControllerSearchOffsetV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto>): OffsetPaginationDto => r.body)
    );
  }

  /** Path part for operation `userManagementControllerSearchCursorV1()` */
  static readonly UserManagementControllerSearchCursorV1Path = '/api/v1/user-management/search/cursor';

  /**
   * 사용자 커서 기반 조회.
   *
   * 사용자를 커서 기반으로 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userManagementControllerSearchCursorV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerSearchCursorV1$Response(params?: UserManagementControllerSearchCursorV1$Params, context?: HttpContext): Observable<StrictHttpResponse<CursorPaginationDto>> {
    return userManagementControllerSearchCursorV1(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 커서 기반 조회.
   *
   * 사용자를 커서 기반으로 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userManagementControllerSearchCursorV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerSearchCursorV1(params?: UserManagementControllerSearchCursorV1$Params, context?: HttpContext): Observable<CursorPaginationDto> {
    return this.userManagementControllerSearchCursorV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<CursorPaginationDto>): CursorPaginationDto => r.body)
    );
  }

  /** Path part for operation `userManagementControllerFindByIdV1()` */
  static readonly UserManagementControllerFindByIdV1Path = '/api/v1/user-management/{id}';

  /**
   * 사용자 상세 조회.
   *
   * 사용자 상세 정보를 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userManagementControllerFindByIdV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerFindByIdV1$Response(params: UserManagementControllerFindByIdV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userManagementControllerFindByIdV1(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 상세 조회.
   *
   * 사용자 상세 정보를 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userManagementControllerFindByIdV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerFindByIdV1(params: UserManagementControllerFindByIdV1$Params, context?: HttpContext): Observable<UserDto> {
    return this.userManagementControllerFindByIdV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userManagementControllerRemoveV1()` */
  static readonly UserManagementControllerRemoveV1Path = '/api/v1/user-management/{id}';

  /**
   * 사용자 삭제.
   *
   * 관리자가 사용자를 삭제합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userManagementControllerRemoveV1()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerRemoveV1$Response(params: UserManagementControllerRemoveV1$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userManagementControllerRemoveV1(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 삭제.
   *
   * 관리자가 사용자를 삭제합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userManagementControllerRemoveV1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userManagementControllerRemoveV1(params: UserManagementControllerRemoveV1$Params, context?: HttpContext): Observable<boolean> {
    return this.userManagementControllerRemoveV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userManagementControllerUpdateV1()` */
  static readonly UserManagementControllerUpdateV1Path = '/api/v1/user-management/{id}';

  /**
   * 사용자 수정.
   *
   * 관리자가 사용자를 수정합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userManagementControllerUpdateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userManagementControllerUpdateV1$Response(params: UserManagementControllerUpdateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userManagementControllerUpdateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 수정.
   *
   * 관리자가 사용자를 수정합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userManagementControllerUpdateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userManagementControllerUpdateV1(params: UserManagementControllerUpdateV1$Params, context?: HttpContext): Observable<UserDto> {
    return this.userManagementControllerUpdateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `userManagementControllerCreateV1()` */
  static readonly UserManagementControllerCreateV1Path = '/api/v1/user-management';

  /**
   * 사용자 생성.
   *
   * 관리자가 사용자를 생성합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userManagementControllerCreateV1()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userManagementControllerCreateV1$Response(params: UserManagementControllerCreateV1$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    return userManagementControllerCreateV1(this.http, this.rootUrl, params, context);
  }

  /**
   * 사용자 생성.
   *
   * 관리자가 사용자를 생성합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userManagementControllerCreateV1$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userManagementControllerCreateV1(params: UserManagementControllerCreateV1$Params, context?: HttpContext): Observable<UserDto> {
    return this.userManagementControllerCreateV1$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

}
