import { Prisma } from '@prisma/client';
import { Bid_Service } from '../types/bid-service.type';
import dayjs from 'dayjs';
import { OpenAPIEntity } from '../../openapi.entity.abstract.class';

export class BidServiceEntity extends OpenAPIEntity {
  constructor(private data: Bid_Service) {
    super();
  }

  toCreateInput(): Prisma.Bid_ServiceCreateInput {
    return {
      id: this.data.bidNtceNo,
      입찰공고명: this.data.bidNtceNm,
      입찰공고차수: parseInt(this.data.bidNtceOrd),
      재공고여부: this.data.reNtceYn === 'Y',
      등록유형명: this.data.rgstTyNm,
      공고종류명: this.data.ntceKindNm,
      국제입찰여부: this.data.intrbidYn === 'Y',
      입찰공고일시: this.data.bidNtceDt !== '' ? dayjs(this.data.bidNtceDt).toDate() : null,
      참조번호: this.data.refNo,
      공고기관코드: this.data.ntceInsttCd,
      공고기관명: this.data.ntceInsttNm,
      수요기관코드: this.data.dminsttCd,
      수요기관명: this.data.dminsttNm,
      입찰방식명: this.data.bidMethdNm,
      계약체결방법명: this.data.cntrctCnclsMthdNm,
      공고기관담당자명: this.data.ntceInsttOfclNm,
      공고기관담당자전화번호: this.data.ntceInsttOfclTelNo,
      공고기관담당자이메일주소: this.data.ntceInsttOfclEmailAdrs,
      집행관명: this.data.exctvNm,
      입찰참가자격등록마감일시: this.data.bidQlfctRgstDt !== '' ? dayjs(this.data.bidQlfctRgstDt).toDate() : null,
      공동수급협정서접수방식: this.data.cmmnSpldmdMethdNm,
      공동수급협정마감일시: this.data.cmmnSpldmdAgrmntClseDt !== '' ? dayjs(this.data.cmmnSpldmdAgrmntClseDt).toDate() : null,
      공동수급업체지역제한여부: this.data.cmmnSpldmdCorpRgnLmtYn === 'Y',
      입찰개시일시: this.data.bidBeginDt !== '' ? dayjs(this.data.bidBeginDt).toDate() : null,
      입찰마감일시: this.data.bidClseDt !== '' ? dayjs(this.data.bidClseDt).toDate() : null,
      개찰일시: this.data.opengDt !== '' ? dayjs(this.data.opengDt).toDate() : null,
      공고규격서URL: [
        this.data.ntceSpecDocUrl1,
        this.data.ntceSpecDocUrl2,
        this.data.ntceSpecDocUrl3,
        this.data.ntceSpecDocUrl4,
        this.data.ntceSpecDocUrl5,
        this.data.ntceSpecDocUrl6,
        this.data.ntceSpecDocUrl7,
        this.data.ntceSpecDocUrl8,
        this.data.ntceSpecDocUrl9,
        this.data.ntceSpecDocUrl10,
      ].filter((i) => i !== ''),
      공고규격파일명: [
        this.data.ntceSpecFileNm1,
        this.data.ntceSpecFileNm2,
        this.data.ntceSpecFileNm3,
        this.data.ntceSpecFileNm4,
        this.data.ntceSpecFileNm5,
        this.data.ntceSpecFileNm6,
        this.data.ntceSpecFileNm7,
        this.data.ntceSpecFileNm8,
        this.data.ntceSpecFileNm9,
        this.data.ntceSpecFileNm10,
      ].filter((i) => i !== ''),
      재입찰허용여부: this.data.rbidPermsnYn === 'Y',
      PQ신청서접수방법명: this.data.pqApplDocRcptMthdNm,
      PQ신청서접수일시: this.data.pqApplDocRcptDt !== '' ? dayjs(this.data.pqApplDocRcptDt).toDate() : null,
      TP심사신청방법명: this.data.tpEvalApplMthdNm,
      TP심사신청마감일시: this.data.tpEvalApplClseDt !== '' ? dayjs(this.data.tpEvalApplClseDt).toDate() : null,
      공동도급의무지역명: [
        this.data.jntcontrctDutyRgnNm1,
        this.data.jntcontrctDutyRgnNm2,
        this.data.jntcontrctDutyRgnNm3,
      ].filter((i) => i !== ''),
      지역의무공동도급비율: parseInt(this.data.rgnDutyJntcontrctRt),
      내역입찰여부: this.data.dtlsBidYn === 'Y',
      입찰참가제한여부: this.data.bidPrtcptLmtYn === 'Y',
      예정가격결정방법명: this.data.prearngPrceDcsnMthdNm,
      총예가건수: parseInt(this.data.totPrdprcNum),
      추첨예가건수: parseInt(this.data.drwtPrdprcNum),
      배정예산금액: parseInt(this.data.asignBdgtAmt),
      추정가격: parseInt(this.data.presmptPrce),
      개찰장소: this.data.opengPlce,
      설명회실시일시: this.data.dcmtgOprtnDt !== '' ? dayjs(this.data.dcmtgOprtnDt).toDate() : null,
      설명회실시장소: this.data.dcmtgOprtnPlce,
      입찰공고상세URL: this.data.bidNtceDtlUrl,
      입찰공고URL: this.data.bidNtceUrl,
      입찰참가수수료납부여부: this.data.bidPrtcptFeePaymntYn,
      입찰참가수수료: parseInt(this.data.bidPrtcptFee),
      입찰보증금납부여부: this.data.bidGrntymnyPaymntYn === 'Y',
      채권자명: this.data.crdtrNm,
      조달청일반용역여부: this.data.ppswGnrlSrvceYn === 'Y',
      용역구분명: this.data.srvceDivNm,
      물품분류제한여부: this.data.prdctClsfcLmtYn === 'Y',
      제조여부: this.data.mnfctYn === 'Y',
      구매대상물품목록: this.data.purchsObjPrdctList.split(','),
      통합공고번호: this.data.untyNtceNo,
      공동수급방식코드: this.data.cmmnSpldmdMethdCd,
      공동수급구성방식명: this.data.cmmnSpldmdMethdNm,
      표준공고서URL: this.data.stdNtceDocUrl,
      지사투찰허용여부: this.data.brffcBidprcPermsnYn === 'Y',
      지명경쟁여부: this.data.dsgntCmptYn === 'Y',
      실적경쟁여부: this.data.arsltCmptYn === 'Y',
      PQ심사여부: this.data.pqEvalYn === 'Y',
      TP심사여부: this.data.tpEvalYn === 'Y',
      공고설명여부: this.data.ntceDscrptYn === 'Y',
      예비가격재작성방법명: this.data.prearngPrceDcsnMthdNm,
      실적신청서접수방법명: this.data.arsltApplDocRcptMthdNm,
      실적신청서접수일시: this.data.arsltReqstdocRcptDt !== '' ? dayjs(this.data.arsltReqstdocRcptDt).toDate() : null,
      발주계획통합번호: this.data.orderPlanUntyNo,
      낙찰하한율: parseFloat(this.data.sucsfbidLwltRate),
      등록일시: this.data.rgstDt !== '' ? dayjs(this.data.rgstDt).toDate() : null,
      사전규격등록번호: this.data.bfSpecRgstNo,
      정보화사업여부: this.data.infoBizYn === 'Y',
      낙찰방법코드: this.data.sucsfbidMthdCd,
      낙찰방법명: this.data.sucsfbidMthdNm,
      수요기관담당자이메일주소: this.data.dminsttOfclEmailAdrs,
      업종제한여부: this.data.indstrytyLmtYn === 'Y',
      변경공고사유: this.data.chgNtceRsn,
      재입찰개찰일시: this.data.rbidOpengDt !== '' ? dayjs(this.data.rbidOpengDt).toDate() : null,
      부가가치세: parseInt(this.data.VAT),
      주공종부가가치세: parseInt(this.data.indutyVAT),
      공공조달대분류명: this.data.pubPrcrmntClsfcNm,
      공공조달중분류명: this.data.pubPrcrmntMidClsfcNm,
      공공조달분류번호: this.data.pubPrcrmntClsfcNo,
      공공조달분류명: this.data.pubPrcrmntClsfcNm,
    };
  }
}
