name: Deploy Prod

on:
  push:
    branches: ["main"]
    paths:
      - "apps/**"
      - "docker/**"
      - "libs/**"
      - ".github/workflows/deploy_prod.yaml"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch:
env:
  service_name: bidly
  ENVIRONMENT: production

jobs:
  detect-changes:
    runs-on: self-hosted
    outputs:
      admin: ${{ steps.filter.outputs.admin }}
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            admin:
              - 'apps/admin/**'
              - 'docker/Dockerfile.admin'
              - 'libs/**'
              - '.github/workflows/deploy_prod.yaml'
              - 'package.json'
              - 'package-lock.json'
            client:
              - 'apps/client/**'
              - 'docker/Dockerfile.client'
              - 'libs/**'
              - '.github/workflows/deploy_prod.yaml'
              - 'package.json'
              - 'package-lock.json'
            server:
              - 'apps/server/**'
              - 'docker/Dockerfile.server'
              - 'libs/**'
              - '.github/workflows/deploy_prod.yaml'
              - 'package.json'
              - 'package-lock.json'

  deploy_admin:
    runs-on: self-hosted
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.admin == 'true' }}
    env:
      app_name: admin
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install --force
          npm install @angular/material --force

      - name: Build Application
        run: npx nx build ${{env.app_name}} --configuration production --skip-nx-cache

      - name: Build Docker Image
        run: docker build --build-arg environment=${{env.ENVIRONMENT}} -t lepisode/${{env.service_name}}-${{env.app_name}}:latest -f docker/Dockerfile.${{env.app_name}} .

      - name: Export Docker Image to File
        run: docker save lepisode/${{env.service_name}}-${{env.app_name}}:latest -o ${{env.app_name}}_image.tar

      - name: Upload Docker Image to Remote Host
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{secrets.REMOTE_HOST}}
          port: ${{secrets.REMOTE_PORT}}
          username: ${{secrets.REMOTE_USER}}
          password: ${{secrets.REMOTE_PASSWORD}}
          source: ${{env.app_name}}_image.tar
          target: /home/${{secrets.REMOTE_USER}}/

  deploy_client:
    runs-on: self-hosted
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.client == 'true' }}
    env:
      app_name: client
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          npm install --force
          npm install @angular/material --force

      - name: Build Application
        run: npx nx build ${{env.app_name}} --configuration production --skip-nx-cache

      - name: Build Docker Image
        run: docker build --build-arg environment=production -t lepisode/${{env.service_name}}-${{env.app_name}}:latest -f docker/Dockerfile.${{env.app_name}} .

      - name: Export Docker Image to File
        run: docker save lepisode/${{env.service_name}}-${{env.app_name}}:latest -o ${{env.app_name}}_image.tar

      - name: Upload Docker Image to Remote Host
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{secrets.REMOTE_HOST}}
          port: ${{secrets.REMOTE_PORT}}
          username: ${{secrets.REMOTE_USER}}
          password: ${{secrets.REMOTE_PASSWORD}}
          source: ${{env.app_name}}_image.tar
          target: /home/${{secrets.REMOTE_USER}}/

  deploy_server:
    runs-on: self-hosted
    needs: [detect-changes]
    if: ${{ needs.detect-changes.outputs.server == 'true' }}
    env:
      app_name: server
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install --force

      - name: Login Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.LEPISODE_DOCKER_USERNAME}}
          password: ${{secrets.LEPISODE_DOCKER_PASSWORD}}

      - name: Build Application
        run: npx nx build ${{env.app_name}} --configuration production --skip-nx-cache

      - name: Build Docker Image
        run: docker build --build-arg environment=${{env.ENVIRONMENT}} -t lepisode/${{env.service_name}}-${{env.app_name}}:latest -f docker/Dockerfile.${{env.app_name}} .

      - name: Export Docker Image to File
        run: docker save lepisode/${{env.service_name}}-${{env.app_name}}:latest -o ${{env.app_name}}_image.tar

      - name: Upload Docker Image to Remote Host
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{secrets.REMOTE_HOST}}
          port: ${{secrets.REMOTE_PORT}}
          username: ${{secrets.REMOTE_USER}}
          password: ${{secrets.REMOTE_PASSWORD}}
          source: ${{env.app_name}}_image.tar
          target: /home/${{secrets.REMOTE_USER}}/

  restart_stack:
    runs-on: self-hosted
    needs: ["deploy_admin", "deploy_client", "deploy_server"]
    if: ${{always()}}
    steps:
      - name: Load Docker Image on Remote Host
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{secrets.REMOTE_HOST}}
          port: ${{secrets.REMOTE_PORT}}
          username: ${{secrets.REMOTE_USER}}
          password: ${{secrets.REMOTE_PASSWORD}}
          script: |
            if [ -f admin_image.tar ]; then docker load -i admin_image.tar; fi
            if [ -f client_image.tar ]; then docker load -i client_image.tar; fi
            if [ -f server_image.tar ]; then docker load -i server_image.tar; fi
            docker compose up -d
            docker system prune -f
            if [ -f admin_image.tar ]; then rm admin_image.tar; fi
            if [ -f client_image.tar ]; then rm client_image.tar; fi
            if [ -f server_image.tar ]; then rm server_image.tar; fi
