/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PreStandardDto } from '../../models/pre-standard-dto';

export interface PreStandardControllerGetLatestLog$Params {
}

export function preStandardControllerGetLatestLog(http: HttpClient, rootUrl: string, params?: PreStandardControllerGetLatestLog$Params, context?: HttpContext): Observable<StrictHttpResponse<PreStandardDto>> {
  const rb = new RequestBuilder(rootUrl, preStandardControllerGetLatestLog.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PreStandardDto>;
    })
  );
}

preStandardControllerGetLatestLog.PATH = '/api/pre-standard/log/latest';
