/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BidConstructionDto } from '../../models/bid-construction-dto';
import { BidEtcDto } from '../../models/bid-etc-dto';
import { BidForeignDto } from '../../models/bid-foreign-dto';
import { BidServiceDto } from '../../models/bid-service-dto';
import { BidThingDto } from '../../models/bid-thing-dto';

export interface BidControllerFindById$Params {
  id: string;
}

export function bidControllerFindById(http: HttpClient, rootUrl: string, params: BidControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<(BidConstructionDto | BidEtcDto | BidForeignDto | BidServiceDto | BidThingDto)>> {
  const rb = new RequestBuilder(rootUrl, bidControllerFindById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(BidConstructionDto | BidEtcDto | BidForeignDto | BidServiceDto | BidThingDto)>;
    })
  );
}

bidControllerFindById.PATH = '/api/bid/{id}';
