/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CursorPaginationDto } from '../models/cursor-pagination-dto';
import { menuControllerCreate } from '../fn/menu/menu-controller-create';
import { MenuControllerCreate$Params } from '../fn/menu/menu-controller-create';
import { menuControllerCreatePermission } from '../fn/menu/menu-controller-create-permission';
import { MenuControllerCreatePermission$Params } from '../fn/menu/menu-controller-create-permission';
import { menuControllerDelete } from '../fn/menu/menu-controller-delete';
import { MenuControllerDelete$Params } from '../fn/menu/menu-controller-delete';
import { menuControllerDeletePermission } from '../fn/menu/menu-controller-delete-permission';
import { MenuControllerDeletePermission$Params } from '../fn/menu/menu-controller-delete-permission';
import { menuControllerFindAll } from '../fn/menu/menu-controller-find-all';
import { MenuControllerFindAll$Params } from '../fn/menu/menu-controller-find-all';
import { menuControllerFindById } from '../fn/menu/menu-controller-find-by-id';
import { MenuControllerFindById$Params } from '../fn/menu/menu-controller-find-by-id';
import { menuControllerSearchCursor } from '../fn/menu/menu-controller-search-cursor';
import { MenuControllerSearchCursor$Params } from '../fn/menu/menu-controller-search-cursor';
import { menuControllerSearchOffset } from '../fn/menu/menu-controller-search-offset';
import { MenuControllerSearchOffset$Params } from '../fn/menu/menu-controller-search-offset';
import { menuControllerUpdate } from '../fn/menu/menu-controller-update';
import { MenuControllerUpdate$Params } from '../fn/menu/menu-controller-update';
import { menuControllerUpdatePermission } from '../fn/menu/menu-controller-update-permission';
import { MenuControllerUpdatePermission$Params } from '../fn/menu/menu-controller-update-permission';
import { MenuDto } from '../models/menu-dto';
import { MenuPermissionDto } from '../models/menu-permission-dto';
import { OffsetPaginationDto } from '../models/offset-pagination-dto';

@Injectable({ providedIn: 'root' })
export class MenuService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `menuControllerFindAll()` */
  static readonly MenuControllerFindAllPath = '/api/menu';

  /**
   * 메뉴 전체 조회.
   *
   * 메뉴 전체를 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerFindAll$Response(params?: MenuControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MenuDto>>> {
    return menuControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 전체 조회.
   *
   * 메뉴 전체를 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerFindAll(params?: MenuControllerFindAll$Params, context?: HttpContext): Observable<Array<MenuDto>> {
    return this.menuControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<MenuDto>>): Array<MenuDto> => r.body)
    );
  }

  /** Path part for operation `menuControllerCreate()` */
  static readonly MenuControllerCreatePath = '/api/menu';

  /**
   * 메뉴 생성.
   *
   * 메뉴을(를) 생성합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerCreate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreate$Response(params: MenuControllerCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuDto>> {
    return menuControllerCreate(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 생성.
   *
   * 메뉴을(를) 생성합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerCreate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreate(params: MenuControllerCreate$Params, context?: HttpContext): Observable<MenuDto> {
    return this.menuControllerCreate$Response(params, context).pipe(
      map((r: StrictHttpResponse<MenuDto>): MenuDto => r.body)
    );
  }

  /** Path part for operation `menuControllerSearchOffset()` */
  static readonly MenuControllerSearchOffsetPath = '/api/menu/search/offset';

  /**
   * 메뉴 오프셋 기반 조회.
   *
   * 메뉴을(를) 오프셋 기반으로 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerSearchOffset()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerSearchOffset$Response(params: MenuControllerSearchOffset$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto>> {
    return menuControllerSearchOffset(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 오프셋 기반 조회.
   *
   * 메뉴을(를) 오프셋 기반으로 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerSearchOffset$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerSearchOffset(params: MenuControllerSearchOffset$Params, context?: HttpContext): Observable<OffsetPaginationDto> {
    return this.menuControllerSearchOffset$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto>): OffsetPaginationDto => r.body)
    );
  }

  /** Path part for operation `menuControllerSearchCursor()` */
  static readonly MenuControllerSearchCursorPath = '/api/menu/search/cursor';

  /**
   * 메뉴 커서 기반 조회.
   *
   * 메뉴을(를) 커서 기반으로 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerSearchCursor()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerSearchCursor$Response(params: MenuControllerSearchCursor$Params, context?: HttpContext): Observable<StrictHttpResponse<CursorPaginationDto>> {
    return menuControllerSearchCursor(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 커서 기반 조회.
   *
   * 메뉴을(를) 커서 기반으로 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerSearchCursor$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerSearchCursor(params: MenuControllerSearchCursor$Params, context?: HttpContext): Observable<CursorPaginationDto> {
    return this.menuControllerSearchCursor$Response(params, context).pipe(
      map((r: StrictHttpResponse<CursorPaginationDto>): CursorPaginationDto => r.body)
    );
  }

  /** Path part for operation `menuControllerFindById()` */
  static readonly MenuControllerFindByIdPath = '/api/menu/{id}';

  /**
   * 메뉴 ID 기반 조회.
   *
   * 메뉴을(를) ID를 기반으로 조회합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerFindById()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerFindById$Response(params: MenuControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuDto>> {
    return menuControllerFindById(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 ID 기반 조회.
   *
   * 메뉴을(를) ID를 기반으로 조회합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerFindById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerFindById(params: MenuControllerFindById$Params, context?: HttpContext): Observable<MenuDto> {
    return this.menuControllerFindById$Response(params, context).pipe(
      map((r: StrictHttpResponse<MenuDto>): MenuDto => r.body)
    );
  }

  /** Path part for operation `menuControllerDelete()` */
  static readonly MenuControllerDeletePath = '/api/menu/{id}';

  /**
   * 메뉴 삭제.
   *
   * 메뉴을(를) 삭제합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDelete$Response(params: MenuControllerDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuDto>> {
    return menuControllerDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 삭제.
   *
   * 메뉴을(를) 삭제합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDelete(params: MenuControllerDelete$Params, context?: HttpContext): Observable<MenuDto> {
    return this.menuControllerDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<MenuDto>): MenuDto => r.body)
    );
  }

  /** Path part for operation `menuControllerUpdate()` */
  static readonly MenuControllerUpdatePath = '/api/menu/{id}';

  /**
   * 메뉴 수정.
   *
   * 메뉴을(를) 수정합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerUpdate()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdate$Response(params: MenuControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuDto>> {
    return menuControllerUpdate(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 수정.
   *
   * 메뉴을(를) 수정합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerUpdate$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdate(params: MenuControllerUpdate$Params, context?: HttpContext): Observable<MenuDto> {
    return this.menuControllerUpdate$Response(params, context).pipe(
      map((r: StrictHttpResponse<MenuDto>): MenuDto => r.body)
    );
  }

  /** Path part for operation `menuControllerCreatePermission()` */
  static readonly MenuControllerCreatePermissionPath = '/api/menu/permission';

  /**
   * 메뉴 권한 생성.
   *
   * 메뉴 권한을(를) 생성합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerCreatePermission()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreatePermission$Response(params: MenuControllerCreatePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuPermissionDto>> {
    return menuControllerCreatePermission(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 권한 생성.
   *
   * 메뉴 권한을(를) 생성합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerCreatePermission$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerCreatePermission(params: MenuControllerCreatePermission$Params, context?: HttpContext): Observable<MenuPermissionDto> {
    return this.menuControllerCreatePermission$Response(params, context).pipe(
      map((r: StrictHttpResponse<MenuPermissionDto>): MenuPermissionDto => r.body)
    );
  }

  /** Path part for operation `menuControllerDeletePermission()` */
  static readonly MenuControllerDeletePermissionPath = '/api/menu/permission/{permissionId}';

  /**
   * 메뉴 권한 삭제.
   *
   * 메뉴 권한을(를) 삭제합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerDeletePermission()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeletePermission$Response(params: MenuControllerDeletePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuPermissionDto>> {
    return menuControllerDeletePermission(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 권한 삭제.
   *
   * 메뉴 권한을(를) 삭제합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerDeletePermission$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  menuControllerDeletePermission(params: MenuControllerDeletePermission$Params, context?: HttpContext): Observable<MenuPermissionDto> {
    return this.menuControllerDeletePermission$Response(params, context).pipe(
      map((r: StrictHttpResponse<MenuPermissionDto>): MenuPermissionDto => r.body)
    );
  }

  /** Path part for operation `menuControllerUpdatePermission()` */
  static readonly MenuControllerUpdatePermissionPath = '/api/menu/permission/{permissionId}';

  /**
   * 메뉴 권한 수정.
   *
   * 메뉴 권한을(를) 수정합니다.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `menuControllerUpdatePermission()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdatePermission$Response(params: MenuControllerUpdatePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuPermissionDto>> {
    return menuControllerUpdatePermission(this.http, this.rootUrl, params, context);
  }

  /**
   * 메뉴 권한 수정.
   *
   * 메뉴 권한을(를) 수정합니다.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `menuControllerUpdatePermission$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  menuControllerUpdatePermission(params: MenuControllerUpdatePermission$Params, context?: HttpContext): Observable<MenuPermissionDto> {
    return this.menuControllerUpdatePermission$Response(params, context).pipe(
      map((r: StrictHttpResponse<MenuPermissionDto>): MenuPermissionDto => r.body)
    );
  }

}
