/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OffsetPaginationDto } from '../models/offset-pagination-dto';
import { OpenApiSyncLogDto } from '../models/open-api-sync-log-dto';
import { orderPlanControllerDownload } from '../fn/order-plan/order-plan-controller-download';
import { OrderPlanControllerDownload$Params } from '../fn/order-plan/order-plan-controller-download';
import { orderPlanControllerFindById } from '../fn/order-plan/order-plan-controller-find-by-id';
import { OrderPlanControllerFindById$Params } from '../fn/order-plan/order-plan-controller-find-by-id';
import { orderPlanControllerGetBookmarked } from '../fn/order-plan/order-plan-controller-get-bookmarked';
import { OrderPlanControllerGetBookmarked$Params } from '../fn/order-plan/order-plan-controller-get-bookmarked';
import { orderPlanControllerGetLatestLog } from '../fn/order-plan/order-plan-controller-get-latest-log';
import { OrderPlanControllerGetLatestLog$Params } from '../fn/order-plan/order-plan-controller-get-latest-log';
import { orderPlanControllerSearch } from '../fn/order-plan/order-plan-controller-search';
import { OrderPlanControllerSearch$Params } from '../fn/order-plan/order-plan-controller-search';
import { orderPlanControllerSyncOrderPlans } from '../fn/order-plan/order-plan-controller-sync-order-plans';
import { OrderPlanControllerSyncOrderPlans$Params } from '../fn/order-plan/order-plan-controller-sync-order-plans';
import { orderPlanControllerUpdateKeywords } from '../fn/order-plan/order-plan-controller-update-keywords';
import { OrderPlanControllerUpdateKeywords$Params } from '../fn/order-plan/order-plan-controller-update-keywords';
import { OrderPlanDto } from '../models/order-plan-dto';

@Injectable({ providedIn: 'root' })
export class OrderPlanService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `orderPlanControllerSearch()` */
  static readonly OrderPlanControllerSearchPath = '/api/order-plan/search';

  /**
   * 발주계획 검색.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderPlanControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerSearch$Response(params: OrderPlanControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
}>> {
    return orderPlanControllerSearch(this.http, this.rootUrl, params, context);
  }

  /**
   * 발주계획 검색.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderPlanControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerSearch(params: OrderPlanControllerSearch$Params, context?: HttpContext): Observable<OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
}> {
    return this.orderPlanControllerSearch$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
}>): OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
} => r.body)
    );
  }

  /** Path part for operation `orderPlanControllerGetBookmarked()` */
  static readonly OrderPlanControllerGetBookmarkedPath = '/api/order-plan/bookmark';

  /**
   * 즐겨찾기한 발주계획 검색.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderPlanControllerGetBookmarked()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerGetBookmarked$Response(params: OrderPlanControllerGetBookmarked$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
}>> {
    return orderPlanControllerGetBookmarked(this.http, this.rootUrl, params, context);
  }

  /**
   * 즐겨찾기한 발주계획 검색.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderPlanControllerGetBookmarked$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerGetBookmarked(params: OrderPlanControllerGetBookmarked$Params, context?: HttpContext): Observable<OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
}> {
    return this.orderPlanControllerGetBookmarked$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
}>): OffsetPaginationDto & {
'items'?: Array<OrderPlanDto>;
} => r.body)
    );
  }

  /** Path part for operation `orderPlanControllerFindById()` */
  static readonly OrderPlanControllerFindByIdPath = '/api/order-plan/{id}';

  /**
   * 발주계획 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderPlanControllerFindById()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerFindById$Response(params: OrderPlanControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderPlanDto>> {
    return orderPlanControllerFindById(this.http, this.rootUrl, params, context);
  }

  /**
   * 발주계획 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderPlanControllerFindById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerFindById(params: OrderPlanControllerFindById$Params, context?: HttpContext): Observable<OrderPlanDto> {
    return this.orderPlanControllerFindById$Response(params, context).pipe(
      map((r: StrictHttpResponse<OrderPlanDto>): OrderPlanDto => r.body)
    );
  }

  /** Path part for operation `orderPlanControllerGetLatestLog()` */
  static readonly OrderPlanControllerGetLatestLogPath = '/api/order-plan/log/latest';

  /**
   * 최근 동기화 로그 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderPlanControllerGetLatestLog()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerGetLatestLog$Response(params?: OrderPlanControllerGetLatestLog$Params, context?: HttpContext): Observable<StrictHttpResponse<OpenApiSyncLogDto>> {
    return orderPlanControllerGetLatestLog(this.http, this.rootUrl, params, context);
  }

  /**
   * 최근 동기화 로그 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderPlanControllerGetLatestLog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerGetLatestLog(params?: OrderPlanControllerGetLatestLog$Params, context?: HttpContext): Observable<OpenApiSyncLogDto> {
    return this.orderPlanControllerGetLatestLog$Response(params, context).pipe(
      map((r: StrictHttpResponse<OpenApiSyncLogDto>): OpenApiSyncLogDto => r.body)
    );
  }

  /** Path part for operation `orderPlanControllerSyncOrderPlans()` */
  static readonly OrderPlanControllerSyncOrderPlansPath = '/api/order-plan/sync';

  /**
   * 발주계획 수동 동기화.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderPlanControllerSyncOrderPlans()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerSyncOrderPlans$Response(params?: OrderPlanControllerSyncOrderPlans$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return orderPlanControllerSyncOrderPlans(this.http, this.rootUrl, params, context);
  }

  /**
   * 발주계획 수동 동기화.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderPlanControllerSyncOrderPlans$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  orderPlanControllerSyncOrderPlans(params?: OrderPlanControllerSyncOrderPlans$Params, context?: HttpContext): Observable<void> {
    return this.orderPlanControllerSyncOrderPlans$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `orderPlanControllerDownload()` */
  static readonly OrderPlanControllerDownloadPath = '/api/order-plan/download';

  /**
   * 입찰공고 파일 다운로드.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderPlanControllerDownload()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderPlanControllerDownload$Response(params: OrderPlanControllerDownload$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return orderPlanControllerDownload(this.http, this.rootUrl, params, context);
  }

  /**
   * 입찰공고 파일 다운로드.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderPlanControllerDownload$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderPlanControllerDownload(params: OrderPlanControllerDownload$Params, context?: HttpContext): Observable<Blob> {
    return this.orderPlanControllerDownload$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `orderPlanControllerUpdateKeywords()` */
  static readonly OrderPlanControllerUpdateKeywordsPath = '/api/order-plan/{id}/keywords';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `orderPlanControllerUpdateKeywords()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderPlanControllerUpdateKeywords$Response(params: OrderPlanControllerUpdateKeywords$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return orderPlanControllerUpdateKeywords(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `orderPlanControllerUpdateKeywords$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  orderPlanControllerUpdateKeywords(params: OrderPlanControllerUpdateKeywords$Params, context?: HttpContext): Observable<void> {
    return this.orderPlanControllerUpdateKeywords$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
