/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { FileInfoResponseDto } from '../models/file-info-response-dto';
import { OffsetPaginationDto } from '../models/offset-pagination-dto';
import { preStandardControllerDownload } from '../fn/pre-standard/pre-standard-controller-download';
import { PreStandardControllerDownload$Params } from '../fn/pre-standard/pre-standard-controller-download';
import { preStandardControllerFindById } from '../fn/pre-standard/pre-standard-controller-find-by-id';
import { PreStandardControllerFindById$Params } from '../fn/pre-standard/pre-standard-controller-find-by-id';
import { preStandardControllerGetBookmarked } from '../fn/pre-standard/pre-standard-controller-get-bookmarked';
import { PreStandardControllerGetBookmarked$Params } from '../fn/pre-standard/pre-standard-controller-get-bookmarked';
import { preStandardControllerGetFileInfo } from '../fn/pre-standard/pre-standard-controller-get-file-info';
import { PreStandardControllerGetFileInfo$Params } from '../fn/pre-standard/pre-standard-controller-get-file-info';
import { preStandardControllerGetLatestLog } from '../fn/pre-standard/pre-standard-controller-get-latest-log';
import { PreStandardControllerGetLatestLog$Params } from '../fn/pre-standard/pre-standard-controller-get-latest-log';
import { preStandardControllerSearch } from '../fn/pre-standard/pre-standard-controller-search';
import { PreStandardControllerSearch$Params } from '../fn/pre-standard/pre-standard-controller-search';
import { preStandardControllerSync } from '../fn/pre-standard/pre-standard-controller-sync';
import { PreStandardControllerSync$Params } from '../fn/pre-standard/pre-standard-controller-sync';
import { preStandardControllerUpdateKeywords } from '../fn/pre-standard/pre-standard-controller-update-keywords';
import { PreStandardControllerUpdateKeywords$Params } from '../fn/pre-standard/pre-standard-controller-update-keywords';
import { PreStandardDto } from '../models/pre-standard-dto';

@Injectable({ providedIn: 'root' })
export class PreStandardService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `preStandardControllerGetFileInfo()` */
  static readonly PreStandardControllerGetFileInfoPath = '/api/pre-standard/file-info';

  /**
   * 파일 URL 정보 조회 (파일명 추출).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerGetFileInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerGetFileInfo$Response(params: PreStandardControllerGetFileInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponseDto>> {
    return preStandardControllerGetFileInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * 파일 URL 정보 조회 (파일명 추출).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerGetFileInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerGetFileInfo(params: PreStandardControllerGetFileInfo$Params, context?: HttpContext): Observable<FileInfoResponseDto> {
    return this.preStandardControllerGetFileInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<FileInfoResponseDto>): FileInfoResponseDto => r.body)
    );
  }

  /** Path part for operation `preStandardControllerSearch()` */
  static readonly PreStandardControllerSearchPath = '/api/pre-standard/search';

  /**
   * 사전규격 공고 검색.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerSearch()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerSearch$Response(params: PreStandardControllerSearch$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
}>> {
    return preStandardControllerSearch(this.http, this.rootUrl, params, context);
  }

  /**
   * 사전규격 공고 검색.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerSearch$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerSearch(params: PreStandardControllerSearch$Params, context?: HttpContext): Observable<OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
}> {
    return this.preStandardControllerSearch$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
}>): OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
} => r.body)
    );
  }

  /** Path part for operation `preStandardControllerGetBookmarked()` */
  static readonly PreStandardControllerGetBookmarkedPath = '/api/pre-standard/bookmark';

  /**
   * 즐겨찾기한 발주계획 검색.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerGetBookmarked()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerGetBookmarked$Response(params: PreStandardControllerGetBookmarked$Params, context?: HttpContext): Observable<StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
}>> {
    return preStandardControllerGetBookmarked(this.http, this.rootUrl, params, context);
  }

  /**
   * 즐겨찾기한 발주계획 검색.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerGetBookmarked$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerGetBookmarked(params: PreStandardControllerGetBookmarked$Params, context?: HttpContext): Observable<OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
}> {
    return this.preStandardControllerGetBookmarked$Response(params, context).pipe(
      map((r: StrictHttpResponse<OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
}>): OffsetPaginationDto & {
'items'?: Array<PreStandardDto>;
} => r.body)
    );
  }

  /** Path part for operation `preStandardControllerGetLatestLog()` */
  static readonly PreStandardControllerGetLatestLogPath = '/api/pre-standard/log/latest';

  /**
   * 최근 동기화 로그 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerGetLatestLog()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerGetLatestLog$Response(params?: PreStandardControllerGetLatestLog$Params, context?: HttpContext): Observable<StrictHttpResponse<PreStandardDto>> {
    return preStandardControllerGetLatestLog(this.http, this.rootUrl, params, context);
  }

  /**
   * 최근 동기화 로그 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerGetLatestLog$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerGetLatestLog(params?: PreStandardControllerGetLatestLog$Params, context?: HttpContext): Observable<PreStandardDto> {
    return this.preStandardControllerGetLatestLog$Response(params, context).pipe(
      map((r: StrictHttpResponse<PreStandardDto>): PreStandardDto => r.body)
    );
  }

  /** Path part for operation `preStandardControllerFindById()` */
  static readonly PreStandardControllerFindByIdPath = '/api/pre-standard/{id}';

  /**
   * 사전규격 공고 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerFindById()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerFindById$Response(params: PreStandardControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<PreStandardDto>> {
    return preStandardControllerFindById(this.http, this.rootUrl, params, context);
  }

  /**
   * 사전규격 공고 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerFindById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerFindById(params: PreStandardControllerFindById$Params, context?: HttpContext): Observable<PreStandardDto> {
    return this.preStandardControllerFindById$Response(params, context).pipe(
      map((r: StrictHttpResponse<PreStandardDto>): PreStandardDto => r.body)
    );
  }

  /** Path part for operation `preStandardControllerSync()` */
  static readonly PreStandardControllerSyncPath = '/api/pre-standard/sync';

  /**
   * 사전규격 공고 동기화.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerSync()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerSync$Response(params?: PreStandardControllerSync$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return preStandardControllerSync(this.http, this.rootUrl, params, context);
  }

  /**
   * 사전규격 공고 동기화.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerSync$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  preStandardControllerSync(params?: PreStandardControllerSync$Params, context?: HttpContext): Observable<void> {
    return this.preStandardControllerSync$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `preStandardControllerDownload()` */
  static readonly PreStandardControllerDownloadPath = '/api/pre-standard/download';

  /**
   * 입찰공고 파일 다운로드.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerDownload()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  preStandardControllerDownload$Response(params: PreStandardControllerDownload$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return preStandardControllerDownload(this.http, this.rootUrl, params, context);
  }

  /**
   * 입찰공고 파일 다운로드.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerDownload$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  preStandardControllerDownload(params: PreStandardControllerDownload$Params, context?: HttpContext): Observable<Blob> {
    return this.preStandardControllerDownload$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `preStandardControllerUpdateKeywords()` */
  static readonly PreStandardControllerUpdateKeywordsPath = '/api/pre-standard/{id}/keywords';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `preStandardControllerUpdateKeywords()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  preStandardControllerUpdateKeywords$Response(params: PreStandardControllerUpdateKeywords$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return preStandardControllerUpdateKeywords(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `preStandardControllerUpdateKeywords$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  preStandardControllerUpdateKeywords(params: PreStandardControllerUpdateKeywords$Params, context?: HttpContext): Observable<void> {
    return this.preStandardControllerUpdateKeywords$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
