/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { RoleDto } from '../models/role-dto';
import { userRoleControllerCreatePermission } from '../fn/user-role/user-role-controller-create-permission';
import { UserRoleControllerCreatePermission$Params } from '../fn/user-role/user-role-controller-create-permission';
import { userRoleControllerCreateRole } from '../fn/user-role/user-role-controller-create-role';
import { UserRoleControllerCreateRole$Params } from '../fn/user-role/user-role-controller-create-role';
import { userRoleControllerDeletePermission } from '../fn/user-role/user-role-controller-delete-permission';
import { UserRoleControllerDeletePermission$Params } from '../fn/user-role/user-role-controller-delete-permission';
import { userRoleControllerDeleteRole } from '../fn/user-role/user-role-controller-delete-role';
import { UserRoleControllerDeleteRole$Params } from '../fn/user-role/user-role-controller-delete-role';
import { userRoleControllerFindAll } from '../fn/user-role/user-role-controller-find-all';
import { UserRoleControllerFindAll$Params } from '../fn/user-role/user-role-controller-find-all';
import { userRoleControllerUpdatePermission } from '../fn/user-role/user-role-controller-update-permission';
import { UserRoleControllerUpdatePermission$Params } from '../fn/user-role/user-role-controller-update-permission';
import { userRoleControllerUpdateRole } from '../fn/user-role/user-role-controller-update-role';
import { UserRoleControllerUpdateRole$Params } from '../fn/user-role/user-role-controller-update-role';

@Injectable({ providedIn: 'root' })
export class UserRoleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `userRoleControllerFindAll()` */
  static readonly UserRoleControllerFindAllPath = '/api/user-role';

  /**
   * 역할 조회.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userRoleControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  userRoleControllerFindAll$Response(params?: UserRoleControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleDto>>> {
    return userRoleControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * 역할 조회.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userRoleControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userRoleControllerFindAll(params?: UserRoleControllerFindAll$Params, context?: HttpContext): Observable<Array<RoleDto>> {
    return this.userRoleControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoleDto>>): Array<RoleDto> => r.body)
    );
  }

  /** Path part for operation `userRoleControllerCreateRole()` */
  static readonly UserRoleControllerCreateRolePath = '/api/user-role';

  /**
   * 역할 생성.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userRoleControllerCreateRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerCreateRole$Response(params: UserRoleControllerCreateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return userRoleControllerCreateRole(this.http, this.rootUrl, params, context);
  }

  /**
   * 역할 생성.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userRoleControllerCreateRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerCreateRole(params: UserRoleControllerCreateRole$Params, context?: HttpContext): Observable<void> {
    return this.userRoleControllerCreateRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `userRoleControllerCreatePermission()` */
  static readonly UserRoleControllerCreatePermissionPath = '/api/user-role/permission';

  /**
   * 권한 생성.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userRoleControllerCreatePermission()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerCreatePermission$Response(params: UserRoleControllerCreatePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return userRoleControllerCreatePermission(this.http, this.rootUrl, params, context);
  }

  /**
   * 권한 생성.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userRoleControllerCreatePermission$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerCreatePermission(params: UserRoleControllerCreatePermission$Params, context?: HttpContext): Observable<void> {
    return this.userRoleControllerCreatePermission$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `userRoleControllerDeleteRole()` */
  static readonly UserRoleControllerDeleteRolePath = '/api/user-role/{id}';

  /**
   * 역할 삭제.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userRoleControllerDeleteRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  userRoleControllerDeleteRole$Response(params: UserRoleControllerDeleteRole$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userRoleControllerDeleteRole(this.http, this.rootUrl, params, context);
  }

  /**
   * 역할 삭제.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userRoleControllerDeleteRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userRoleControllerDeleteRole(params: UserRoleControllerDeleteRole$Params, context?: HttpContext): Observable<boolean> {
    return this.userRoleControllerDeleteRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userRoleControllerUpdateRole()` */
  static readonly UserRoleControllerUpdateRolePath = '/api/user-role/{id}';

  /**
   * 역할 수정.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userRoleControllerUpdateRole()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerUpdateRole$Response(params: UserRoleControllerUpdateRole$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return userRoleControllerUpdateRole(this.http, this.rootUrl, params, context);
  }

  /**
   * 역할 수정.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userRoleControllerUpdateRole$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerUpdateRole(params: UserRoleControllerUpdateRole$Params, context?: HttpContext): Observable<void> {
    return this.userRoleControllerUpdateRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `userRoleControllerDeletePermission()` */
  static readonly UserRoleControllerDeletePermissionPath = '/api/user-role/permission/{permissionId}';

  /**
   * 권한 삭제.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userRoleControllerDeletePermission()` instead.
   *
   * This method doesn't expect any request body.
   */
  userRoleControllerDeletePermission$Response(params: UserRoleControllerDeletePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return userRoleControllerDeletePermission(this.http, this.rootUrl, params, context);
  }

  /**
   * 권한 삭제.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userRoleControllerDeletePermission$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  userRoleControllerDeletePermission(params: UserRoleControllerDeletePermission$Params, context?: HttpContext): Observable<boolean> {
    return this.userRoleControllerDeletePermission$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `userRoleControllerUpdatePermission()` */
  static readonly UserRoleControllerUpdatePermissionPath = '/api/user-role/permission/{permissionId}';

  /**
   * 권한 수정.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `userRoleControllerUpdatePermission()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerUpdatePermission$Response(params: UserRoleControllerUpdatePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return userRoleControllerUpdatePermission(this.http, this.rootUrl, params, context);
  }

  /**
   * 권한 수정.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `userRoleControllerUpdatePermission$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  userRoleControllerUpdatePermission(params: UserRoleControllerUpdatePermission$Params, context?: HttpContext): Observable<void> {
    return this.userRoleControllerUpdatePermission$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
