/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateRoleLevelPermissionDto } from '../../models/update-role-level-permission-dto';

export interface UserRoleControllerUpdatePermission$Params {
  permissionId: string;
      body: UpdateRoleLevelPermissionDto
}

export function userRoleControllerUpdatePermission(http: HttpClient, rootUrl: string, params: UserRoleControllerUpdatePermission$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, userRoleControllerUpdatePermission.PATH, 'patch');
  if (params) {
    rb.path('permissionId', params.permissionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

userRoleControllerUpdatePermission.PATH = '/api/user-role/permission/{permissionId}';
