/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileInfoResponseDto } from '../../models/file-info-response-dto';

export interface PreStandardControllerGetFileInfo$Params {
  url: string;
}

export function preStandardControllerGetFileInfo(http: HttpClient, rootUrl: string, params: PreStandardControllerGetFileInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<FileInfoResponseDto>> {
  const rb = new RequestBuilder(rootUrl, preStandardControllerGetFileInfo.PATH, 'get');
  if (params) {
    rb.query('url', params.url, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileInfoResponseDto>;
    })
  );
}

preStandardControllerGetFileInfo.PATH = '/api/pre-standard/file-info';
