FROM node

WORKDIR /app

ARG environment

COPY dist/apps/server /app
COPY prisma /app/prisma
COPY apps/server/.env.${environment} /app/.env

RUN npm install --force
RUN npx prisma@6.15.0 generate --schema prisma

CMD ["node", "main.js"]

EXPOSE 3000
