/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderPlanDto } from '../../models/order-plan-dto';

export interface OrderPlanControllerFindById$Params {
  id: string;
}

export function orderPlanControllerFindById(http: HttpClient, rootUrl: string, params: OrderPlanControllerFindById$Params, context?: HttpContext): Observable<StrictHttpResponse<OrderPlanDto>> {
  const rb = new RequestBuilder(rootUrl, orderPlanControllerFindById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrderPlanDto>;
    })
  );
}

orderPlanControllerFindById.PATH = '/api/order-plan/{id}';
