/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OpenApiSyncLogDto } from '../../models/open-api-sync-log-dto';

export interface OrderPlanControllerGetLatestLog$Params {
}

export function orderPlanControllerGetLatestLog(http: HttpClient, rootUrl: string, params?: OrderPlanControllerGetLatestLog$Params, context?: HttpContext): Observable<StrictHttpResponse<OpenApiSyncLogDto>> {
  const rb = new RequestBuilder(rootUrl, orderPlanControllerGetLatestLog.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OpenApiSyncLogDto>;
    })
  );
}

orderPlanControllerGetLatestLog.PATH = '/api/order-plan/log/latest';
