/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuDto } from '../../models/menu-dto';

export interface MenuControllerFindAll$Params {

/**
 * 검색어
 */
  query?: string;

/**
 * 메뉴 ID
 */
  id?: string;
}

export function menuControllerFindAll(http: HttpClient, rootUrl: string, params?: MenuControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MenuDto>>> {
  const rb = new RequestBuilder(rootUrl, menuControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
    rb.query('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MenuDto>>;
    })
  );
}

menuControllerFindAll.PATH = '/api/menu';
