/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MenuDto } from '../../models/menu-dto';

export interface MenuControllerDelete$Params {
  id: string;
}

export function menuControllerDelete(http: HttpClient, rootUrl: string, params: MenuControllerDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<MenuDto>> {
  const rb = new RequestBuilder(rootUrl, menuControllerDelete.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MenuDto>;
    })
  );
}

menuControllerDelete.PATH = '/api/menu/{id}';
