/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StatisticDto } from '../../models/statistic-dto';

export interface StatisticControllerFindStatistic$Params {
}

export function statisticControllerFindStatistic(http: HttpClient, rootUrl: string, params?: StatisticControllerFindStatistic$Params, context?: HttpContext): Observable<StrictHttpResponse<StatisticDto>> {
  const rb = new RequestBuilder(rootUrl, statisticControllerFindStatistic.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StatisticDto>;
    })
  );
}

statisticControllerFindStatistic.PATH = '/api/statistics';
